// Code generated by ent, DO NOT EDIT.

package oauthauthorizationcode

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/schema"
)

const (
	// Label holds the string label denoting the oauthauthorizationcode type in the database.
	Label = "oauth_authorization_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCodeHash holds the string denoting the code_hash field in the database.
	FieldCodeHash = "code_hash"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldClientName holds the string denoting the client_name field in the database.
	FieldClientName = "client_name"
	// FieldClientKind holds the string denoting the client_kind field in the database.
	FieldClientKind = "client_kind"
	// FieldClientURI holds the string denoting the client_uri field in the database.
	FieldClientURI = "client_uri"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldCodeChallenge holds the string denoting the code_challenge field in the database.
	FieldCodeChallenge = "code_challenge"
	// FieldResource holds the string denoting the resource field in the database.
	FieldResource = "resource"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldFullAccess holds the string denoting the full_access field in the database.
	FieldFullAccess = "full_access"
	// FieldResources holds the string denoting the resources field in the database.
	FieldResources = "resources"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldGrantID holds the string denoting the grant_id field in the database.
	FieldGrantID = "grant_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the oauthauthorizationcode in the database.
	Table = "oauth_authorization_codes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "oauth_authorization_codes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for oauthauthorizationcode fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCodeHash,
	FieldClientID,
	FieldClientName,
	FieldClientKind,
	FieldClientURI,
	FieldRedirectURI,
	FieldCodeChallenge,
	FieldResource,
	FieldScope,
	FieldRole,
	FieldFullAccess,
	FieldResources,
	FieldExpiresAt,
	FieldUsedAt,
	FieldGrantID,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultFullAccess holds the default value on creation for the "full_access" field.
	DefaultFullAccess bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ClientKindValidator is a validator for the "client_kind" field enum values. It is called by the builders before save.
func ClientKindValidator(ck schema.OAuthClientKind) error {
	switch ck {
	case "dynamic", "metadata_document":
		return nil
	default:
		return fmt.Errorf("oauthauthorizationcode: invalid enum value for client_kind field: %q", ck)
	}
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r schema.PermittedAction) error {
	switch r {
	case "admin", "editor", "viewer":
		return nil
	default:
		return fmt.Errorf("oauthauthorizationcode: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the OAuthAuthorizationCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCodeHash orders the results by the code_hash field.
func ByCodeHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeHash, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByClientName orders the results by the client_name field.
func ByClientName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientName, opts...).ToFunc()
}

// ByClientKind orders the results by the client_kind field.
func ByClientKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientKind, opts...).ToFunc()
}

// ByClientURI orders the results by the client_uri field.
func ByClientURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientURI, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByCodeChallenge orders the results by the code_challenge field.
func ByCodeChallenge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeChallenge, opts...).ToFunc()
}

// ByResource orders the results by the resource field.
func ByResource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResource, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByFullAccess orders the results by the full_access field.
func ByFullAccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullAccess, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByGrantID orders the results by the grant_id field.
func ByGrantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
