import BrandIcon from "@/components/icons/brand";
import {
  Block,
  BlockItem,
  BlockItemButtonLike,
  BlockItemContent,
  BlockItemHeader,
  BlockItemTitle,
} from "@/components/service/panel/content/undeployed/block";
import DomainPortBlock from "@/components/service/panel/content/undeployed/blocks/domain-port-block";
import VariablesBlock from "@/components/service/panel/content/undeployed/blocks/variables-block";
import DeployButtonSection from "@/components/service/panel/content/undeployed/deploy-button-section";
import { WrapperForm, WrapperInner } from "@/components/service/panel/content/undeployed/wrapper";
import { useSystem } from "@/components/system/system-provider";
import { cn } from "@/components/ui/utils";
import { generateDomain } from "@/lib/helpers/generate-domain";
import { useAppForm } from "@/lib/hooks/use-app-form";
import { TVariableForCreate } from "@/server/trpc/api/variables/types";
import { api } from "@/server/trpc/setup/client";
import { GitBranchIcon } from "lucide-react";
import { useMemo } from "react";
import { toast } from "sonner";

type TProps = {
  repo: string;
  owner: string;
  branch: string;
  installationId: number;
  detectedPort: string | undefined;
};

export function UndeployedContentGit({
  repo,
  owner,
  branch,
  installationId,
  detectedPort,
}: TProps) {
  const { data: systemData } = useSystem();
  const wildcardUrl = systemData?.data.system_settings.wildcard_domain;
  const wildcardDomain = wildcardUrl ? new URL(wildcardUrl).hostname : undefined;
  const autoGeneratedDomain = useMemo(() => {
    if (!wildcardDomain) return undefined;
    const domain = generateDomain(repo, wildcardDomain);
    return domain;
  }, [wildcardDomain, repo]);

  const form = useAppForm({
    defaultValues: {
      branch: branch,
      domain: autoGeneratedDomain || "",
      isPublic: true,
      port: detectedPort !== undefined ? detectedPort : "",
      variables: [{ name: "", value: "" }] as TVariableForCreate[],
    },
    onSubmit: ({ value }) => {
      toast.info("Submitted", {
        description: JSON.stringify(value, null, 2),
      });
    },
  });

  const {
    data: dataRepository,
    isPending: isPendingRepository,
    error: errorRepository,
  } = api.git.getRepository.useQuery({
    owner,
    repoName: repo,
    installationId,
  });

  return (
    <WrapperForm
      onSubmit={(e) => {
        e.preventDefault();
        form.handleSubmit(e);
      }}
    >
      <WrapperInner>
        {/* Repository and Branch */}
        <Block>
          {/* Repository */}
          <BlockItem>
            <BlockItemHeader>
              <BlockItemTitle>Repository</BlockItemTitle>
            </BlockItemHeader>
            <BlockItemContent>
              <BlockItemButtonLike
                asElement="div"
                text={`${owner}/${repo}`}
                Icon={({ className }) => (
                  <BrandIcon brand="github" color="brand" className={className} />
                )}
              />
            </BlockItemContent>
          </BlockItem>
          {/* Branch */}
          <BlockItem>
            <BlockItemHeader>
              <BlockItemTitle>Branch</BlockItemTitle>
            </BlockItemHeader>
            <BlockItemContent>
              <form.AppField
                name="branch"
                children={(field) => (
                  <field.AsyncDropdown
                    dontCheckUntilSubmit
                    field={field}
                    value={field.state.value}
                    onChange={(v) => field.handleChange(v)}
                    items={dataRepository?.repository.branches?.map((b) => b.name)}
                    isPending={isPendingRepository}
                    error={errorRepository?.message}
                    commandInputPlaceholder="Search branches..."
                    commandEmptyText="No branches found"
                    CommandEmptyIcon={GitBranchIcon}
                  >
                    {({ isOpen }) => (
                      <BlockItemButtonLike
                        asElement="button"
                        text={field.state.value}
                        Icon={({ className }) => (
                          <GitBranchIcon className={cn("scale-90", className)} />
                        )}
                        variant="outline"
                        open={isOpen}
                        onBlur={field.handleBlur}
                      />
                    )}
                  </field.AsyncDropdown>
                )}
              />
            </BlockItemContent>
          </BlockItem>
        </Block>
        <DomainPortBlock
          // @ts-expect-error: This type is completely fine. The form here encapculates the domain & port only form but it doesn't work for some reason
          form={form}
          detectedPort={detectedPort}
          autoGeneratedDomain={autoGeneratedDomain}
        />
        {/* @ts-expect-error: This type is completely fine. The form here encapculates the variable only form but it doesn't work for some reason */}
        <VariablesBlock form={form} />
      </WrapperInner>
      <DeployButtonSection isPending={false} />
    </WrapperForm>
  );
}
