// Code generated by ent, DO NOT EDIT.

package oauthgranttoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/predicate"
	"github.com/unbindapp/unbind-api/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldExpiresAt, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldUsedAt, v))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldGrantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v schema.OAuthTokenKind) predicate.OAuthGrantToken {
	vc := v
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldKind, vc))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v schema.OAuthTokenKind) predicate.OAuthGrantToken {
	vc := v
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldKind, vc))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...schema.OAuthTokenKind) predicate.OAuthGrantToken {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OAuthGrantToken(sql.FieldIn(FieldKind, v...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...schema.OAuthTokenKind) predicate.OAuthGrantToken {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldKind, v...))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldContainsFold(FieldTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLTE(FieldExpiresAt, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotNull(FieldUsedAt))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...uuid.UUID) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.FieldNotIn(FieldGrantID, vs...))
}

// HasGrant applies the HasEdge predicate on the "grant" edge.
func HasGrant() predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GrantTable, GrantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGrantWith applies the HasEdge predicate on the "grant" edge with a given conditions (other predicates).
func HasGrantWith(preds ...predicate.OAuthGrant) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(func(s *sql.Selector) {
		step := newGrantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthGrantToken) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthGrantToken) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthGrantToken) predicate.OAuthGrantToken {
	return predicate.OAuthGrantToken(sql.NotPredicates(p))
}
