// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/environment"
	"github.com/unbindapp/unbind-api/ent/predicate"
	"github.com/unbindapp/unbind-api/ent/project"
	"github.com/unbindapp/unbind-api/ent/service"
	"github.com/unbindapp/unbind-api/ent/servicegroup"
)

// EnvironmentUpdate is the builder for updating Environment entities.
type EnvironmentUpdate struct {
	config
	hooks     []Hook
	mutation  *EnvironmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EnvironmentUpdate builder.
func (_u *EnvironmentUpdate) Where(ps ...predicate.Environment) *EnvironmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvironmentUpdate) SetUpdatedAt(v time.Time) *EnvironmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKubernetesName sets the "kubernetes_name" field.
func (_u *EnvironmentUpdate) SetKubernetesName(v string) *EnvironmentUpdate {
	_u.mutation.SetKubernetesName(v)
	return _u
}

// SetNillableKubernetesName sets the "kubernetes_name" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableKubernetesName(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetKubernetesName(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EnvironmentUpdate) SetName(v string) *EnvironmentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableName(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EnvironmentUpdate) SetDescription(v string) *EnvironmentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableDescription(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EnvironmentUpdate) ClearDescription() *EnvironmentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetActive sets the "active" field.
func (_u *EnvironmentUpdate) SetActive(v bool) *EnvironmentUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableActive(v *bool) *EnvironmentUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EnvironmentUpdate) SetProjectID(v uuid.UUID) *EnvironmentUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableProjectID(v *uuid.UUID) *EnvironmentUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetKubernetesSecret sets the "kubernetes_secret" field.
func (_u *EnvironmentUpdate) SetKubernetesSecret(v string) *EnvironmentUpdate {
	_u.mutation.SetKubernetesSecret(v)
	return _u
}

// SetNillableKubernetesSecret sets the "kubernetes_secret" field if the given value is not nil.
func (_u *EnvironmentUpdate) SetNillableKubernetesSecret(v *string) *EnvironmentUpdate {
	if v != nil {
		_u.SetKubernetesSecret(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EnvironmentUpdate) SetProject(v *Project) *EnvironmentUpdate {
	return _u.SetProjectID(v.ID)
}

// AddServiceIDs adds the "services" edge to the Service entity by IDs.
func (_u *EnvironmentUpdate) AddServiceIDs(ids ...uuid.UUID) *EnvironmentUpdate {
	_u.mutation.AddServiceIDs(ids...)
	return _u
}

// AddServices adds the "services" edges to the Service entity.
func (_u *EnvironmentUpdate) AddServices(v ...*Service) *EnvironmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServiceIDs(ids...)
}

// AddProjectDefaultIDs adds the "project_default" edge to the Project entity by IDs.
func (_u *EnvironmentUpdate) AddProjectDefaultIDs(ids ...uuid.UUID) *EnvironmentUpdate {
	_u.mutation.AddProjectDefaultIDs(ids...)
	return _u
}

// AddProjectDefault adds the "project_default" edges to the Project entity.
func (_u *EnvironmentUpdate) AddProjectDefault(v ...*Project) *EnvironmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectDefaultIDs(ids...)
}

// AddServiceGroupIDs adds the "service_groups" edge to the ServiceGroup entity by IDs.
func (_u *EnvironmentUpdate) AddServiceGroupIDs(ids ...uuid.UUID) *EnvironmentUpdate {
	_u.mutation.AddServiceGroupIDs(ids...)
	return _u
}

// AddServiceGroups adds the "service_groups" edges to the ServiceGroup entity.
func (_u *EnvironmentUpdate) AddServiceGroups(v ...*ServiceGroup) *EnvironmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServiceGroupIDs(ids...)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_u *EnvironmentUpdate) Mutation() *EnvironmentMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EnvironmentUpdate) ClearProject() *EnvironmentUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearServices clears all "services" edges to the Service entity.
func (_u *EnvironmentUpdate) ClearServices() *EnvironmentUpdate {
	_u.mutation.ClearServices()
	return _u
}

// RemoveServiceIDs removes the "services" edge to Service entities by IDs.
func (_u *EnvironmentUpdate) RemoveServiceIDs(ids ...uuid.UUID) *EnvironmentUpdate {
	_u.mutation.RemoveServiceIDs(ids...)
	return _u
}

// RemoveServices removes "services" edges to Service entities.
func (_u *EnvironmentUpdate) RemoveServices(v ...*Service) *EnvironmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServiceIDs(ids...)
}

// ClearProjectDefault clears all "project_default" edges to the Project entity.
func (_u *EnvironmentUpdate) ClearProjectDefault() *EnvironmentUpdate {
	_u.mutation.ClearProjectDefault()
	return _u
}

// RemoveProjectDefaultIDs removes the "project_default" edge to Project entities by IDs.
func (_u *EnvironmentUpdate) RemoveProjectDefaultIDs(ids ...uuid.UUID) *EnvironmentUpdate {
	_u.mutation.RemoveProjectDefaultIDs(ids...)
	return _u
}

// RemoveProjectDefault removes "project_default" edges to Project entities.
func (_u *EnvironmentUpdate) RemoveProjectDefault(v ...*Project) *EnvironmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectDefaultIDs(ids...)
}

// ClearServiceGroups clears all "service_groups" edges to the ServiceGroup entity.
func (_u *EnvironmentUpdate) ClearServiceGroups() *EnvironmentUpdate {
	_u.mutation.ClearServiceGroups()
	return _u
}

// RemoveServiceGroupIDs removes the "service_groups" edge to ServiceGroup entities by IDs.
func (_u *EnvironmentUpdate) RemoveServiceGroupIDs(ids ...uuid.UUID) *EnvironmentUpdate {
	_u.mutation.RemoveServiceGroupIDs(ids...)
	return _u
}

// RemoveServiceGroups removes "service_groups" edges to ServiceGroup entities.
func (_u *EnvironmentUpdate) RemoveServiceGroups(v ...*ServiceGroup) *EnvironmentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServiceGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvironmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvironmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvironmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvironmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvironmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := environment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvironmentUpdate) check() error {
	if v, ok := _u.mutation.KubernetesName(); ok {
		if err := environment.KubernetesNameValidator(v); err != nil {
			return &ValidationError{Name: "kubernetes_name", err: fmt.Errorf(`ent: validator failed for field "Environment.kubernetes_name": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Environment.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EnvironmentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EnvironmentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EnvironmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(environment.Table, environment.Columns, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KubernetesName(); ok {
		_spec.SetField(environment.FieldKubernetesName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(environment.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(environment.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(environment.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KubernetesSecret(); ok {
		_spec.SetField(environment.FieldKubernetesSecret, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServicesIDs(); len(nodes) > 0 && !_u.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectDefaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectDefaultIDs(); len(nodes) > 0 && !_u.mutation.ProjectDefaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectDefaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServiceGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServiceGroupsIDs(); len(nodes) > 0 && !_u.mutation.ServiceGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{environment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvironmentUpdateOne is the builder for updating a single Environment entity.
type EnvironmentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EnvironmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvironmentUpdateOne) SetUpdatedAt(v time.Time) *EnvironmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKubernetesName sets the "kubernetes_name" field.
func (_u *EnvironmentUpdateOne) SetKubernetesName(v string) *EnvironmentUpdateOne {
	_u.mutation.SetKubernetesName(v)
	return _u
}

// SetNillableKubernetesName sets the "kubernetes_name" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableKubernetesName(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetKubernetesName(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EnvironmentUpdateOne) SetName(v string) *EnvironmentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableName(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *EnvironmentUpdateOne) SetDescription(v string) *EnvironmentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableDescription(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *EnvironmentUpdateOne) ClearDescription() *EnvironmentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetActive sets the "active" field.
func (_u *EnvironmentUpdateOne) SetActive(v bool) *EnvironmentUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableActive(v *bool) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EnvironmentUpdateOne) SetProjectID(v uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableProjectID(v *uuid.UUID) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetKubernetesSecret sets the "kubernetes_secret" field.
func (_u *EnvironmentUpdateOne) SetKubernetesSecret(v string) *EnvironmentUpdateOne {
	_u.mutation.SetKubernetesSecret(v)
	return _u
}

// SetNillableKubernetesSecret sets the "kubernetes_secret" field if the given value is not nil.
func (_u *EnvironmentUpdateOne) SetNillableKubernetesSecret(v *string) *EnvironmentUpdateOne {
	if v != nil {
		_u.SetKubernetesSecret(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EnvironmentUpdateOne) SetProject(v *Project) *EnvironmentUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddServiceIDs adds the "services" edge to the Service entity by IDs.
func (_u *EnvironmentUpdateOne) AddServiceIDs(ids ...uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.AddServiceIDs(ids...)
	return _u
}

// AddServices adds the "services" edges to the Service entity.
func (_u *EnvironmentUpdateOne) AddServices(v ...*Service) *EnvironmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServiceIDs(ids...)
}

// AddProjectDefaultIDs adds the "project_default" edge to the Project entity by IDs.
func (_u *EnvironmentUpdateOne) AddProjectDefaultIDs(ids ...uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.AddProjectDefaultIDs(ids...)
	return _u
}

// AddProjectDefault adds the "project_default" edges to the Project entity.
func (_u *EnvironmentUpdateOne) AddProjectDefault(v ...*Project) *EnvironmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectDefaultIDs(ids...)
}

// AddServiceGroupIDs adds the "service_groups" edge to the ServiceGroup entity by IDs.
func (_u *EnvironmentUpdateOne) AddServiceGroupIDs(ids ...uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.AddServiceGroupIDs(ids...)
	return _u
}

// AddServiceGroups adds the "service_groups" edges to the ServiceGroup entity.
func (_u *EnvironmentUpdateOne) AddServiceGroups(v ...*ServiceGroup) *EnvironmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddServiceGroupIDs(ids...)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_u *EnvironmentUpdateOne) Mutation() *EnvironmentMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EnvironmentUpdateOne) ClearProject() *EnvironmentUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearServices clears all "services" edges to the Service entity.
func (_u *EnvironmentUpdateOne) ClearServices() *EnvironmentUpdateOne {
	_u.mutation.ClearServices()
	return _u
}

// RemoveServiceIDs removes the "services" edge to Service entities by IDs.
func (_u *EnvironmentUpdateOne) RemoveServiceIDs(ids ...uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.RemoveServiceIDs(ids...)
	return _u
}

// RemoveServices removes "services" edges to Service entities.
func (_u *EnvironmentUpdateOne) RemoveServices(v ...*Service) *EnvironmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServiceIDs(ids...)
}

// ClearProjectDefault clears all "project_default" edges to the Project entity.
func (_u *EnvironmentUpdateOne) ClearProjectDefault() *EnvironmentUpdateOne {
	_u.mutation.ClearProjectDefault()
	return _u
}

// RemoveProjectDefaultIDs removes the "project_default" edge to Project entities by IDs.
func (_u *EnvironmentUpdateOne) RemoveProjectDefaultIDs(ids ...uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.RemoveProjectDefaultIDs(ids...)
	return _u
}

// RemoveProjectDefault removes "project_default" edges to Project entities.
func (_u *EnvironmentUpdateOne) RemoveProjectDefault(v ...*Project) *EnvironmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectDefaultIDs(ids...)
}

// ClearServiceGroups clears all "service_groups" edges to the ServiceGroup entity.
func (_u *EnvironmentUpdateOne) ClearServiceGroups() *EnvironmentUpdateOne {
	_u.mutation.ClearServiceGroups()
	return _u
}

// RemoveServiceGroupIDs removes the "service_groups" edge to ServiceGroup entities by IDs.
func (_u *EnvironmentUpdateOne) RemoveServiceGroupIDs(ids ...uuid.UUID) *EnvironmentUpdateOne {
	_u.mutation.RemoveServiceGroupIDs(ids...)
	return _u
}

// RemoveServiceGroups removes "service_groups" edges to ServiceGroup entities.
func (_u *EnvironmentUpdateOne) RemoveServiceGroups(v ...*ServiceGroup) *EnvironmentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveServiceGroupIDs(ids...)
}

// Where appends a list predicates to the EnvironmentUpdate builder.
func (_u *EnvironmentUpdateOne) Where(ps ...predicate.Environment) *EnvironmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvironmentUpdateOne) Select(field string, fields ...string) *EnvironmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Environment entity.
func (_u *EnvironmentUpdateOne) Save(ctx context.Context) (*Environment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvironmentUpdateOne) SaveX(ctx context.Context) *Environment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvironmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvironmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvironmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := environment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvironmentUpdateOne) check() error {
	if v, ok := _u.mutation.KubernetesName(); ok {
		if err := environment.KubernetesNameValidator(v); err != nil {
			return &ValidationError{Name: "kubernetes_name", err: fmt.Errorf(`ent: validator failed for field "Environment.kubernetes_name": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Environment.project"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EnvironmentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EnvironmentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EnvironmentUpdateOne) sqlSave(ctx context.Context) (_node *Environment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(environment.Table, environment.Columns, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Environment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, environment.FieldID)
		for _, f := range fields {
			if !environment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != environment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.KubernetesName(); ok {
		_spec.SetField(environment.FieldKubernetesName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(environment.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(environment.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(environment.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KubernetesSecret(); ok {
		_spec.SetField(environment.FieldKubernetesSecret, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServicesIDs(); len(nodes) > 0 && !_u.mutation.ServicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectDefaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectDefaultIDs(); len(nodes) > 0 && !_u.mutation.ProjectDefaultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectDefaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ServiceGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedServiceGroupsIDs(); len(nodes) > 0 && !_u.mutation.ServiceGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Environment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{environment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
