// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/githubapp"
	"github.com/unbindapp/unbind-api/ent/githubinstallation"
	"github.com/unbindapp/unbind-api/ent/predicate"
	"github.com/unbindapp/unbind-api/ent/user"
)

// GithubAppUpdate is the builder for updating GithubApp entities.
type GithubAppUpdate struct {
	config
	hooks     []Hook
	mutation  *GithubAppMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GithubAppUpdate builder.
func (_u *GithubAppUpdate) Where(ps ...predicate.GithubApp) *GithubAppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GithubAppUpdate) SetUpdatedAt(v time.Time) *GithubAppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GithubAppUpdate) SetCreatedBy(v uuid.UUID) *GithubAppUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GithubAppUpdate) SetNillableCreatedBy(v *uuid.UUID) *GithubAppUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *GithubAppUpdate) SetName(v string) *GithubAppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GithubAppUpdate) SetNillableName(v *string) *GithubAppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *GithubAppUpdate) SetClientID(v string) *GithubAppUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *GithubAppUpdate) SetNillableClientID(v *string) *GithubAppUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *GithubAppUpdate) SetClientSecret(v string) *GithubAppUpdate {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *GithubAppUpdate) SetNillableClientSecret(v *string) *GithubAppUpdate {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// SetWebhookSecret sets the "webhook_secret" field.
func (_u *GithubAppUpdate) SetWebhookSecret(v string) *GithubAppUpdate {
	_u.mutation.SetWebhookSecret(v)
	return _u
}

// SetNillableWebhookSecret sets the "webhook_secret" field if the given value is not nil.
func (_u *GithubAppUpdate) SetNillableWebhookSecret(v *string) *GithubAppUpdate {
	if v != nil {
		_u.SetWebhookSecret(*v)
	}
	return _u
}

// SetPrivateKey sets the "private_key" field.
func (_u *GithubAppUpdate) SetPrivateKey(v string) *GithubAppUpdate {
	_u.mutation.SetPrivateKey(v)
	return _u
}

// SetNillablePrivateKey sets the "private_key" field if the given value is not nil.
func (_u *GithubAppUpdate) SetNillablePrivateKey(v *string) *GithubAppUpdate {
	if v != nil {
		_u.SetPrivateKey(*v)
	}
	return _u
}

// AddInstallationIDs adds the "installations" edge to the GithubInstallation entity by IDs.
func (_u *GithubAppUpdate) AddInstallationIDs(ids ...int64) *GithubAppUpdate {
	_u.mutation.AddInstallationIDs(ids...)
	return _u
}

// AddInstallations adds the "installations" edges to the GithubInstallation entity.
func (_u *GithubAppUpdate) AddInstallations(v ...*GithubInstallation) *GithubAppUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstallationIDs(ids...)
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *GithubAppUpdate) SetUsersID(id uuid.UUID) *GithubAppUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *GithubAppUpdate) SetUsers(v *User) *GithubAppUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the GithubAppMutation object of the builder.
func (_u *GithubAppUpdate) Mutation() *GithubAppMutation {
	return _u.mutation
}

// ClearInstallations clears all "installations" edges to the GithubInstallation entity.
func (_u *GithubAppUpdate) ClearInstallations() *GithubAppUpdate {
	_u.mutation.ClearInstallations()
	return _u
}

// RemoveInstallationIDs removes the "installations" edge to GithubInstallation entities by IDs.
func (_u *GithubAppUpdate) RemoveInstallationIDs(ids ...int64) *GithubAppUpdate {
	_u.mutation.RemoveInstallationIDs(ids...)
	return _u
}

// RemoveInstallations removes "installations" edges to GithubInstallation entities.
func (_u *GithubAppUpdate) RemoveInstallations(v ...*GithubInstallation) *GithubAppUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstallationIDs(ids...)
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *GithubAppUpdate) ClearUsers() *GithubAppUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GithubAppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GithubAppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GithubAppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GithubAppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GithubAppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := githubapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GithubAppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := githubapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GithubApp.name": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GithubApp.users"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GithubAppUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GithubAppUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GithubAppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(githubapp.Table, githubapp.Columns, sqlgraph.NewFieldSpec(githubapp.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(githubapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(githubapp.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(githubapp.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(githubapp.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebhookSecret(); ok {
		_spec.SetField(githubapp.FieldWebhookSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKey(); ok {
		_spec.SetField(githubapp.FieldPrivateKey, field.TypeString, value)
	}
	if _u.mutation.InstallationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   githubapp.InstallationsTable,
			Columns: []string{githubapp.InstallationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstallationsIDs(); len(nodes) > 0 && !_u.mutation.InstallationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   githubapp.InstallationsTable,
			Columns: []string{githubapp.InstallationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstallationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   githubapp.InstallationsTable,
			Columns: []string{githubapp.InstallationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubapp.UsersTable,
			Columns: []string{githubapp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubapp.UsersTable,
			Columns: []string{githubapp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{githubapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GithubAppUpdateOne is the builder for updating a single GithubApp entity.
type GithubAppUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GithubAppMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GithubAppUpdateOne) SetUpdatedAt(v time.Time) *GithubAppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GithubAppUpdateOne) SetCreatedBy(v uuid.UUID) *GithubAppUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GithubAppUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *GithubAppUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *GithubAppUpdateOne) SetName(v string) *GithubAppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GithubAppUpdateOne) SetNillableName(v *string) *GithubAppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *GithubAppUpdateOne) SetClientID(v string) *GithubAppUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *GithubAppUpdateOne) SetNillableClientID(v *string) *GithubAppUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *GithubAppUpdateOne) SetClientSecret(v string) *GithubAppUpdateOne {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *GithubAppUpdateOne) SetNillableClientSecret(v *string) *GithubAppUpdateOne {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// SetWebhookSecret sets the "webhook_secret" field.
func (_u *GithubAppUpdateOne) SetWebhookSecret(v string) *GithubAppUpdateOne {
	_u.mutation.SetWebhookSecret(v)
	return _u
}

// SetNillableWebhookSecret sets the "webhook_secret" field if the given value is not nil.
func (_u *GithubAppUpdateOne) SetNillableWebhookSecret(v *string) *GithubAppUpdateOne {
	if v != nil {
		_u.SetWebhookSecret(*v)
	}
	return _u
}

// SetPrivateKey sets the "private_key" field.
func (_u *GithubAppUpdateOne) SetPrivateKey(v string) *GithubAppUpdateOne {
	_u.mutation.SetPrivateKey(v)
	return _u
}

// SetNillablePrivateKey sets the "private_key" field if the given value is not nil.
func (_u *GithubAppUpdateOne) SetNillablePrivateKey(v *string) *GithubAppUpdateOne {
	if v != nil {
		_u.SetPrivateKey(*v)
	}
	return _u
}

// AddInstallationIDs adds the "installations" edge to the GithubInstallation entity by IDs.
func (_u *GithubAppUpdateOne) AddInstallationIDs(ids ...int64) *GithubAppUpdateOne {
	_u.mutation.AddInstallationIDs(ids...)
	return _u
}

// AddInstallations adds the "installations" edges to the GithubInstallation entity.
func (_u *GithubAppUpdateOne) AddInstallations(v ...*GithubInstallation) *GithubAppUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstallationIDs(ids...)
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *GithubAppUpdateOne) SetUsersID(id uuid.UUID) *GithubAppUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *GithubAppUpdateOne) SetUsers(v *User) *GithubAppUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the GithubAppMutation object of the builder.
func (_u *GithubAppUpdateOne) Mutation() *GithubAppMutation {
	return _u.mutation
}

// ClearInstallations clears all "installations" edges to the GithubInstallation entity.
func (_u *GithubAppUpdateOne) ClearInstallations() *GithubAppUpdateOne {
	_u.mutation.ClearInstallations()
	return _u
}

// RemoveInstallationIDs removes the "installations" edge to GithubInstallation entities by IDs.
func (_u *GithubAppUpdateOne) RemoveInstallationIDs(ids ...int64) *GithubAppUpdateOne {
	_u.mutation.RemoveInstallationIDs(ids...)
	return _u
}

// RemoveInstallations removes "installations" edges to GithubInstallation entities.
func (_u *GithubAppUpdateOne) RemoveInstallations(v ...*GithubInstallation) *GithubAppUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstallationIDs(ids...)
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *GithubAppUpdateOne) ClearUsers() *GithubAppUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the GithubAppUpdate builder.
func (_u *GithubAppUpdateOne) Where(ps ...predicate.GithubApp) *GithubAppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GithubAppUpdateOne) Select(field string, fields ...string) *GithubAppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GithubApp entity.
func (_u *GithubAppUpdateOne) Save(ctx context.Context) (*GithubApp, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GithubAppUpdateOne) SaveX(ctx context.Context) *GithubApp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GithubAppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GithubAppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GithubAppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := githubapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GithubAppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := githubapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GithubApp.name": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GithubApp.users"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GithubAppUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GithubAppUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GithubAppUpdateOne) sqlSave(ctx context.Context) (_node *GithubApp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(githubapp.Table, githubapp.Columns, sqlgraph.NewFieldSpec(githubapp.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GithubApp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, githubapp.FieldID)
		for _, f := range fields {
			if !githubapp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != githubapp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(githubapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(githubapp.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(githubapp.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(githubapp.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebhookSecret(); ok {
		_spec.SetField(githubapp.FieldWebhookSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKey(); ok {
		_spec.SetField(githubapp.FieldPrivateKey, field.TypeString, value)
	}
	if _u.mutation.InstallationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   githubapp.InstallationsTable,
			Columns: []string{githubapp.InstallationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstallationsIDs(); len(nodes) > 0 && !_u.mutation.InstallationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   githubapp.InstallationsTable,
			Columns: []string{githubapp.InstallationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstallationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   githubapp.InstallationsTable,
			Columns: []string{githubapp.InstallationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubapp.UsersTable,
			Columns: []string{githubapp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubapp.UsersTable,
			Columns: []string{githubapp.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &GithubApp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{githubapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
