// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/oauthauthorizationcode"
	"github.com/unbindapp/unbind-api/ent/schema"
	"github.com/unbindapp/unbind-api/ent/user"
)

// OAuthAuthorizationCodeCreate is the builder for creating a OAuthAuthorizationCode entity.
type OAuthAuthorizationCodeCreate struct {
	config
	mutation *OAuthAuthorizationCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthAuthorizationCodeCreate) SetCreatedAt(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableCreatedAt(v *time.Time) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthAuthorizationCodeCreate) SetUpdatedAt(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableUpdatedAt(v *time.Time) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *OAuthAuthorizationCodeCreate) SetCodeHash(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthAuthorizationCodeCreate) SetClientID(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientName sets the "client_name" field.
func (_c *OAuthAuthorizationCodeCreate) SetClientName(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetClientName(v)
	return _c
}

// SetClientKind sets the "client_kind" field.
func (_c *OAuthAuthorizationCodeCreate) SetClientKind(v schema.OAuthClientKind) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetClientKind(v)
	return _c
}

// SetClientURI sets the "client_uri" field.
func (_c *OAuthAuthorizationCodeCreate) SetClientURI(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetClientURI(v)
	return _c
}

// SetNillableClientURI sets the "client_uri" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableClientURI(v *string) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetClientURI(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthAuthorizationCodeCreate) SetRedirectURI(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthAuthorizationCodeCreate) SetCodeChallenge(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetResource sets the "resource" field.
func (_c *OAuthAuthorizationCodeCreate) SetResource(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetResource(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *OAuthAuthorizationCodeCreate) SetScope(v string) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableScope(v *string) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *OAuthAuthorizationCodeCreate) SetRole(v schema.PermittedAction) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetFullAccess sets the "full_access" field.
func (_c *OAuthAuthorizationCodeCreate) SetFullAccess(v bool) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetFullAccess(v)
	return _c
}

// SetNillableFullAccess sets the "full_access" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableFullAccess(v *bool) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetFullAccess(*v)
	}
	return _c
}

// SetResources sets the "resources" field.
func (_c *OAuthAuthorizationCodeCreate) SetResources(v []schema.APIKeyResource) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetResources(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthAuthorizationCodeCreate) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *OAuthAuthorizationCodeCreate) SetUsedAt(v time.Time) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableUsedAt(v *time.Time) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetGrantID sets the "grant_id" field.
func (_c *OAuthAuthorizationCodeCreate) SetGrantID(v uuid.UUID) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableGrantID(v *uuid.UUID) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetGrantID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthAuthorizationCodeCreate) SetUserID(v uuid.UUID) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthAuthorizationCodeCreate) SetID(v uuid.UUID) *OAuthAuthorizationCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthAuthorizationCodeCreate) SetNillableID(v *uuid.UUID) *OAuthAuthorizationCodeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OAuthAuthorizationCodeCreate) SetUser(v *User) *OAuthAuthorizationCodeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the OAuthAuthorizationCodeMutation object of the builder.
func (_c *OAuthAuthorizationCodeCreate) Mutation() *OAuthAuthorizationCodeMutation {
	return _c.mutation
}

// Save creates the OAuthAuthorizationCode in the database.
func (_c *OAuthAuthorizationCodeCreate) Save(ctx context.Context) (*OAuthAuthorizationCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAuthorizationCodeCreate) SaveX(ctx context.Context) *OAuthAuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizationCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizationCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAuthorizationCodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthauthorizationcode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthauthorizationcode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FullAccess(); !ok {
		v := oauthauthorizationcode.DefaultFullAccess
		_c.mutation.SetFullAccess(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthauthorizationcode.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAuthorizationCodeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.updated_at"`)}
	}
	if _, ok := _c.mutation.CodeHash(); !ok {
		return &ValidationError{Name: "code_hash", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.code_hash"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.client_id"`)}
	}
	if _, ok := _c.mutation.ClientName(); !ok {
		return &ValidationError{Name: "client_name", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.client_name"`)}
	}
	if _, ok := _c.mutation.ClientKind(); !ok {
		return &ValidationError{Name: "client_kind", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.client_kind"`)}
	}
	if v, ok := _c.mutation.ClientKind(); ok {
		if err := oauthauthorizationcode.ClientKindValidator(v); err != nil {
			return &ValidationError{Name: "client_kind", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.client_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.redirect_uri"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.code_challenge"`)}
	}
	if _, ok := _c.mutation.Resource(); !ok {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.resource"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := oauthauthorizationcode.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OAuthAuthorizationCode.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullAccess(); !ok {
		return &ValidationError{Name: "full_access", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.full_access"`)}
	}
	if _, ok := _c.mutation.Resources(); !ok {
		return &ValidationError{Name: "resources", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.resources"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.expires_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthAuthorizationCode.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OAuthAuthorizationCode.user"`)}
	}
	return nil
}

func (_c *OAuthAuthorizationCodeCreate) sqlSave(ctx context.Context) (*OAuthAuthorizationCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAuthorizationCodeCreate) createSpec() (*OAuthAuthorizationCode, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAuthorizationCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthauthorizationcode.Table, sqlgraph.NewFieldSpec(oauthauthorizationcode.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientName(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientName, field.TypeString, value)
		_node.ClientName = value
	}
	if value, ok := _c.mutation.ClientKind(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientKind, field.TypeEnum, value)
		_node.ClientKind = value
	}
	if value, ok := _c.mutation.ClientURI(); ok {
		_spec.SetField(oauthauthorizationcode.FieldClientURI, field.TypeString, value)
		_node.ClientURI = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorizationcode.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.Resource(); ok {
		_spec.SetField(oauthauthorizationcode.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(oauthauthorizationcode.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(oauthauthorizationcode.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.FullAccess(); ok {
		_spec.SetField(oauthauthorizationcode.FieldFullAccess, field.TypeBool, value)
		_node.FullAccess = value
	}
	if value, ok := _c.mutation.Resources(); ok {
		_spec.SetField(oauthauthorizationcode.FieldResources, field.TypeJSON, value)
		_node.Resources = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(oauthauthorizationcode.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.GrantID(); ok {
		_spec.SetField(oauthauthorizationcode.FieldGrantID, field.TypeUUID, value)
		_node.GrantID = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthauthorizationcode.UserTable,
			Columns: []string{oauthauthorizationcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAuthorizationCode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAuthorizationCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthAuthorizationCodeCreate) OnConflict(opts ...sql.ConflictOption) *OAuthAuthorizationCodeUpsertOne {
	_c.conflict = opts
	return &OAuthAuthorizationCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAuthorizationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthAuthorizationCodeCreate) OnConflictColumns(columns ...string) *OAuthAuthorizationCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthAuthorizationCodeUpsertOne{
		create: _c,
	}
}

type (
	// OAuthAuthorizationCodeUpsertOne is the builder for "upsert"-ing
	//  one OAuthAuthorizationCode node.
	OAuthAuthorizationCodeUpsertOne struct {
		create *OAuthAuthorizationCodeCreate
	}

	// OAuthAuthorizationCodeUpsert is the "OnConflict" setter.
	OAuthAuthorizationCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthAuthorizationCodeUpsert) SetUpdatedAt(v time.Time) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateUpdatedAt() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldUpdatedAt)
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *OAuthAuthorizationCodeUpsert) SetCodeHash(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldCodeHash, v)
	return u
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateCodeHash() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldCodeHash)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthAuthorizationCodeUpsert) SetClientID(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateClientID() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldClientID)
	return u
}

// SetClientName sets the "client_name" field.
func (u *OAuthAuthorizationCodeUpsert) SetClientName(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldClientName, v)
	return u
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateClientName() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldClientName)
	return u
}

// SetClientKind sets the "client_kind" field.
func (u *OAuthAuthorizationCodeUpsert) SetClientKind(v schema.OAuthClientKind) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldClientKind, v)
	return u
}

// UpdateClientKind sets the "client_kind" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateClientKind() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldClientKind)
	return u
}

// SetClientURI sets the "client_uri" field.
func (u *OAuthAuthorizationCodeUpsert) SetClientURI(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldClientURI, v)
	return u
}

// UpdateClientURI sets the "client_uri" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateClientURI() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldClientURI)
	return u
}

// ClearClientURI clears the value of the "client_uri" field.
func (u *OAuthAuthorizationCodeUpsert) ClearClientURI() *OAuthAuthorizationCodeUpsert {
	u.SetNull(oauthauthorizationcode.FieldClientURI)
	return u
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthorizationCodeUpsert) SetRedirectURI(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldRedirectURI, v)
	return u
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateRedirectURI() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldRedirectURI)
	return u
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthorizationCodeUpsert) SetCodeChallenge(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldCodeChallenge, v)
	return u
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateCodeChallenge() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldCodeChallenge)
	return u
}

// SetResource sets the "resource" field.
func (u *OAuthAuthorizationCodeUpsert) SetResource(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldResource, v)
	return u
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateResource() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldResource)
	return u
}

// SetScope sets the "scope" field.
func (u *OAuthAuthorizationCodeUpsert) SetScope(v string) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateScope() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldScope)
	return u
}

// ClearScope clears the value of the "scope" field.
func (u *OAuthAuthorizationCodeUpsert) ClearScope() *OAuthAuthorizationCodeUpsert {
	u.SetNull(oauthauthorizationcode.FieldScope)
	return u
}

// SetRole sets the "role" field.
func (u *OAuthAuthorizationCodeUpsert) SetRole(v schema.PermittedAction) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateRole() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldRole)
	return u
}

// SetFullAccess sets the "full_access" field.
func (u *OAuthAuthorizationCodeUpsert) SetFullAccess(v bool) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldFullAccess, v)
	return u
}

// UpdateFullAccess sets the "full_access" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateFullAccess() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldFullAccess)
	return u
}

// SetResources sets the "resources" field.
func (u *OAuthAuthorizationCodeUpsert) SetResources(v []schema.APIKeyResource) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldResources, v)
	return u
}

// UpdateResources sets the "resources" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateResources() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldResources)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthorizationCodeUpsert) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateExpiresAt() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldExpiresAt)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthAuthorizationCodeUpsert) SetUsedAt(v time.Time) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateUsedAt() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthAuthorizationCodeUpsert) ClearUsedAt() *OAuthAuthorizationCodeUpsert {
	u.SetNull(oauthauthorizationcode.FieldUsedAt)
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthAuthorizationCodeUpsert) SetGrantID(v uuid.UUID) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateGrantID() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldGrantID)
	return u
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthAuthorizationCodeUpsert) ClearGrantID() *OAuthAuthorizationCodeUpsert {
	u.SetNull(oauthauthorizationcode.FieldGrantID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthorizationCodeUpsert) SetUserID(v uuid.UUID) *OAuthAuthorizationCodeUpsert {
	u.Set(oauthauthorizationcode.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsert) UpdateUserID() *OAuthAuthorizationCodeUpsert {
	u.SetExcluded(oauthauthorizationcode.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OAuthAuthorizationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthauthorizationcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthAuthorizationCodeUpsertOne) UpdateNewValues() *OAuthAuthorizationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oauthauthorizationcode.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthauthorizationcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAuthorizationCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthAuthorizationCodeUpsertOne) Ignore() *OAuthAuthorizationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAuthorizationCodeUpsertOne) DoNothing() *OAuthAuthorizationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAuthorizationCodeCreate.OnConflict
// documentation for more info.
func (u *OAuthAuthorizationCodeUpsertOne) Update(set func(*OAuthAuthorizationCodeUpsert)) *OAuthAuthorizationCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAuthorizationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetUpdatedAt(v time.Time) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateUpdatedAt() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetCodeHash(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateCodeHash() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetClientID(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateClientID() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetClientName(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateClientName() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientName()
	})
}

// SetClientKind sets the "client_kind" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetClientKind(v schema.OAuthClientKind) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientKind(v)
	})
}

// UpdateClientKind sets the "client_kind" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateClientKind() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientKind()
	})
}

// SetClientURI sets the "client_uri" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetClientURI(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientURI(v)
	})
}

// UpdateClientURI sets the "client_uri" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateClientURI() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientURI()
	})
}

// ClearClientURI clears the value of the "client_uri" field.
func (u *OAuthAuthorizationCodeUpsertOne) ClearClientURI() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearClientURI()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetRedirectURI(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateRedirectURI() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetCodeChallenge(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateCodeChallenge() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetResource sets the "resource" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetResource(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateResource() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateResource()
	})
}

// SetScope sets the "scope" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetScope(v string) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateScope() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *OAuthAuthorizationCodeUpsertOne) ClearScope() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearScope()
	})
}

// SetRole sets the "role" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetRole(v schema.PermittedAction) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateRole() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateRole()
	})
}

// SetFullAccess sets the "full_access" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetFullAccess(v bool) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetFullAccess(v)
	})
}

// UpdateFullAccess sets the "full_access" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateFullAccess() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateFullAccess()
	})
}

// SetResources sets the "resources" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetResources(v []schema.APIKeyResource) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetResources(v)
	})
}

// UpdateResources sets the "resources" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateResources() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateResources()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateExpiresAt() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetUsedAt(v time.Time) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateUsedAt() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthAuthorizationCodeUpsertOne) ClearUsedAt() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetGrantID(v uuid.UUID) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateGrantID() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthAuthorizationCodeUpsertOne) ClearGrantID() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearGrantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthorizationCodeUpsertOne) SetUserID(v uuid.UUID) *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertOne) UpdateUserID() *OAuthAuthorizationCodeUpsertOne {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OAuthAuthorizationCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAuthorizationCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAuthorizationCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthAuthorizationCodeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OAuthAuthorizationCodeUpsertOne.ID is not supported by MySQL driver. Use OAuthAuthorizationCodeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthAuthorizationCodeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthAuthorizationCodeCreateBulk is the builder for creating many OAuthAuthorizationCode entities in bulk.
type OAuthAuthorizationCodeCreateBulk struct {
	config
	err      error
	builders []*OAuthAuthorizationCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthAuthorizationCode entities in the database.
func (_c *OAuthAuthorizationCodeCreateBulk) Save(ctx context.Context) ([]*OAuthAuthorizationCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthAuthorizationCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAuthorizationCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAuthorizationCodeCreateBulk) SaveX(ctx context.Context) []*OAuthAuthorizationCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizationCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizationCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAuthorizationCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAuthorizationCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthAuthorizationCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthAuthorizationCodeUpsertBulk {
	_c.conflict = opts
	return &OAuthAuthorizationCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAuthorizationCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthAuthorizationCodeCreateBulk) OnConflictColumns(columns ...string) *OAuthAuthorizationCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthAuthorizationCodeUpsertBulk{
		create: _c,
	}
}

// OAuthAuthorizationCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthAuthorizationCode nodes.
type OAuthAuthorizationCodeUpsertBulk struct {
	create *OAuthAuthorizationCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthAuthorizationCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthauthorizationcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateNewValues() *OAuthAuthorizationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oauthauthorizationcode.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthauthorizationcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAuthorizationCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthAuthorizationCodeUpsertBulk) Ignore() *OAuthAuthorizationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAuthorizationCodeUpsertBulk) DoNothing() *OAuthAuthorizationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAuthorizationCodeCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthAuthorizationCodeUpsertBulk) Update(set func(*OAuthAuthorizationCodeUpsert)) *OAuthAuthorizationCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAuthorizationCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetUpdatedAt(v time.Time) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateUpdatedAt() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetCodeHash(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateCodeHash() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateCodeHash()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetClientID(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateClientID() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetClientName(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateClientName() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientName()
	})
}

// SetClientKind sets the "client_kind" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetClientKind(v schema.OAuthClientKind) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientKind(v)
	})
}

// UpdateClientKind sets the "client_kind" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateClientKind() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientKind()
	})
}

// SetClientURI sets the "client_uri" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetClientURI(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetClientURI(v)
	})
}

// UpdateClientURI sets the "client_uri" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateClientURI() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateClientURI()
	})
}

// ClearClientURI clears the value of the "client_uri" field.
func (u *OAuthAuthorizationCodeUpsertBulk) ClearClientURI() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearClientURI()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetRedirectURI(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateRedirectURI() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetCodeChallenge(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateCodeChallenge() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetResource sets the "resource" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetResource(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateResource() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateResource()
	})
}

// SetScope sets the "scope" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetScope(v string) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateScope() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *OAuthAuthorizationCodeUpsertBulk) ClearScope() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearScope()
	})
}

// SetRole sets the "role" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetRole(v schema.PermittedAction) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateRole() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateRole()
	})
}

// SetFullAccess sets the "full_access" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetFullAccess(v bool) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetFullAccess(v)
	})
}

// UpdateFullAccess sets the "full_access" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateFullAccess() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateFullAccess()
	})
}

// SetResources sets the "resources" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetResources(v []schema.APIKeyResource) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetResources(v)
	})
}

// UpdateResources sets the "resources" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateResources() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateResources()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetExpiresAt(v time.Time) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateExpiresAt() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetUsedAt(v time.Time) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateUsedAt() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *OAuthAuthorizationCodeUpsertBulk) ClearUsedAt() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearUsedAt()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetGrantID(v uuid.UUID) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateGrantID() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *OAuthAuthorizationCodeUpsertBulk) ClearGrantID() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.ClearGrantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthAuthorizationCodeUpsertBulk) SetUserID(v uuid.UUID) *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthAuthorizationCodeUpsertBulk) UpdateUserID() *OAuthAuthorizationCodeUpsertBulk {
	return u.Update(func(s *OAuthAuthorizationCodeUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OAuthAuthorizationCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthAuthorizationCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAuthorizationCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAuthorizationCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
