// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/oauthgrant"
	"github.com/unbindapp/unbind-api/ent/oauthgranttoken"
	"github.com/unbindapp/unbind-api/ent/schema"
	"github.com/unbindapp/unbind-api/ent/user"
)

// OAuthGrantCreate is the builder for creating a OAuthGrant entity.
type OAuthGrantCreate struct {
	config
	mutation *OAuthGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthGrantCreate) SetCreatedAt(v time.Time) *OAuthGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableCreatedAt(v *time.Time) *OAuthGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthGrantCreate) SetUpdatedAt(v time.Time) *OAuthGrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableUpdatedAt(v *time.Time) *OAuthGrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthGrantCreate) SetClientID(v string) *OAuthGrantCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientName sets the "client_name" field.
func (_c *OAuthGrantCreate) SetClientName(v string) *OAuthGrantCreate {
	_c.mutation.SetClientName(v)
	return _c
}

// SetClientKind sets the "client_kind" field.
func (_c *OAuthGrantCreate) SetClientKind(v schema.OAuthClientKind) *OAuthGrantCreate {
	_c.mutation.SetClientKind(v)
	return _c
}

// SetClientURI sets the "client_uri" field.
func (_c *OAuthGrantCreate) SetClientURI(v string) *OAuthGrantCreate {
	_c.mutation.SetClientURI(v)
	return _c
}

// SetNillableClientURI sets the "client_uri" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableClientURI(v *string) *OAuthGrantCreate {
	if v != nil {
		_c.SetClientURI(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthGrantCreate) SetRedirectURI(v string) *OAuthGrantCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *OAuthGrantCreate) SetRole(v schema.PermittedAction) *OAuthGrantCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetFullAccess sets the "full_access" field.
func (_c *OAuthGrantCreate) SetFullAccess(v bool) *OAuthGrantCreate {
	_c.mutation.SetFullAccess(v)
	return _c
}

// SetNillableFullAccess sets the "full_access" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableFullAccess(v *bool) *OAuthGrantCreate {
	if v != nil {
		_c.SetFullAccess(*v)
	}
	return _c
}

// SetResources sets the "resources" field.
func (_c *OAuthGrantCreate) SetResources(v []schema.APIKeyResource) *OAuthGrantCreate {
	_c.mutation.SetResources(v)
	return _c
}

// SetResource sets the "resource" field.
func (_c *OAuthGrantCreate) SetResource(v string) *OAuthGrantCreate {
	_c.mutation.SetResource(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *OAuthGrantCreate) SetScope(v string) *OAuthGrantCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableScope(v *string) *OAuthGrantCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *OAuthGrantCreate) SetLastUsedAt(v time.Time) *OAuthGrantCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableLastUsedAt(v *time.Time) *OAuthGrantCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *OAuthGrantCreate) SetRevokedAt(v time.Time) *OAuthGrantCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableRevokedAt(v *time.Time) *OAuthGrantCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OAuthGrantCreate) SetUserID(v uuid.UUID) *OAuthGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthGrantCreate) SetID(v uuid.UUID) *OAuthGrantCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthGrantCreate) SetNillableID(v *uuid.UUID) *OAuthGrantCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OAuthGrantCreate) SetUser(v *User) *OAuthGrantCreate {
	return _c.SetUserID(v.ID)
}

// AddTokenIDs adds the "tokens" edge to the OAuthGrantToken entity by IDs.
func (_c *OAuthGrantCreate) AddTokenIDs(ids ...uuid.UUID) *OAuthGrantCreate {
	_c.mutation.AddTokenIDs(ids...)
	return _c
}

// AddTokens adds the "tokens" edges to the OAuthGrantToken entity.
func (_c *OAuthGrantCreate) AddTokens(v ...*OAuthGrantToken) *OAuthGrantCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTokenIDs(ids...)
}

// Mutation returns the OAuthGrantMutation object of the builder.
func (_c *OAuthGrantCreate) Mutation() *OAuthGrantMutation {
	return _c.mutation
}

// Save creates the OAuthGrant in the database.
func (_c *OAuthGrantCreate) Save(ctx context.Context) (*OAuthGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthGrantCreate) SaveX(ctx context.Context) *OAuthGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthGrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthgrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthgrant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FullAccess(); !ok {
		v := oauthgrant.DefaultFullAccess
		_c.mutation.SetFullAccess(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthgrant.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthGrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthGrant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthGrant.updated_at"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthGrant.client_id"`)}
	}
	if _, ok := _c.mutation.ClientName(); !ok {
		return &ValidationError{Name: "client_name", err: errors.New(`ent: missing required field "OAuthGrant.client_name"`)}
	}
	if _, ok := _c.mutation.ClientKind(); !ok {
		return &ValidationError{Name: "client_kind", err: errors.New(`ent: missing required field "OAuthGrant.client_kind"`)}
	}
	if v, ok := _c.mutation.ClientKind(); ok {
		if err := oauthgrant.ClientKindValidator(v); err != nil {
			return &ValidationError{Name: "client_kind", err: fmt.Errorf(`ent: validator failed for field "OAuthGrant.client_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OAuthGrant.redirect_uri"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OAuthGrant.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := oauthgrant.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OAuthGrant.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullAccess(); !ok {
		return &ValidationError{Name: "full_access", err: errors.New(`ent: missing required field "OAuthGrant.full_access"`)}
	}
	if _, ok := _c.mutation.Resources(); !ok {
		return &ValidationError{Name: "resources", err: errors.New(`ent: missing required field "OAuthGrant.resources"`)}
	}
	if _, ok := _c.mutation.Resource(); !ok {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required field "OAuthGrant.resource"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OAuthGrant.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OAuthGrant.user"`)}
	}
	return nil
}

func (_c *OAuthGrantCreate) sqlSave(ctx context.Context) (*OAuthGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthGrantCreate) createSpec() (*OAuthGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthgrant.Table, sqlgraph.NewFieldSpec(oauthgrant.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthgrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthgrant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthgrant.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientName(); ok {
		_spec.SetField(oauthgrant.FieldClientName, field.TypeString, value)
		_node.ClientName = value
	}
	if value, ok := _c.mutation.ClientKind(); ok {
		_spec.SetField(oauthgrant.FieldClientKind, field.TypeEnum, value)
		_node.ClientKind = value
	}
	if value, ok := _c.mutation.ClientURI(); ok {
		_spec.SetField(oauthgrant.FieldClientURI, field.TypeString, value)
		_node.ClientURI = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthgrant.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(oauthgrant.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.FullAccess(); ok {
		_spec.SetField(oauthgrant.FieldFullAccess, field.TypeBool, value)
		_node.FullAccess = value
	}
	if value, ok := _c.mutation.Resources(); ok {
		_spec.SetField(oauthgrant.FieldResources, field.TypeJSON, value)
		_node.Resources = value
	}
	if value, ok := _c.mutation.Resource(); ok {
		_spec.SetField(oauthgrant.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(oauthgrant.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(oauthgrant.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(oauthgrant.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthgrant.UserTable,
			Columns: []string{oauthgrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthgrant.TokensTable,
			Columns: []string{oauthgrant.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthgranttoken.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthGrant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthGrantCreate) OnConflict(opts ...sql.ConflictOption) *OAuthGrantUpsertOne {
	_c.conflict = opts
	return &OAuthGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthGrantCreate) OnConflictColumns(columns ...string) *OAuthGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthGrantUpsertOne{
		create: _c,
	}
}

type (
	// OAuthGrantUpsertOne is the builder for "upsert"-ing
	//  one OAuthGrant node.
	OAuthGrantUpsertOne struct {
		create *OAuthGrantCreate
	}

	// OAuthGrantUpsert is the "OnConflict" setter.
	OAuthGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthGrantUpsert) SetUpdatedAt(v time.Time) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateUpdatedAt() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldUpdatedAt)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthGrantUpsert) SetClientID(v string) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateClientID() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldClientID)
	return u
}

// SetClientName sets the "client_name" field.
func (u *OAuthGrantUpsert) SetClientName(v string) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldClientName, v)
	return u
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateClientName() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldClientName)
	return u
}

// SetClientKind sets the "client_kind" field.
func (u *OAuthGrantUpsert) SetClientKind(v schema.OAuthClientKind) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldClientKind, v)
	return u
}

// UpdateClientKind sets the "client_kind" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateClientKind() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldClientKind)
	return u
}

// SetClientURI sets the "client_uri" field.
func (u *OAuthGrantUpsert) SetClientURI(v string) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldClientURI, v)
	return u
}

// UpdateClientURI sets the "client_uri" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateClientURI() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldClientURI)
	return u
}

// ClearClientURI clears the value of the "client_uri" field.
func (u *OAuthGrantUpsert) ClearClientURI() *OAuthGrantUpsert {
	u.SetNull(oauthgrant.FieldClientURI)
	return u
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthGrantUpsert) SetRedirectURI(v string) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldRedirectURI, v)
	return u
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateRedirectURI() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldRedirectURI)
	return u
}

// SetRole sets the "role" field.
func (u *OAuthGrantUpsert) SetRole(v schema.PermittedAction) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateRole() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldRole)
	return u
}

// SetFullAccess sets the "full_access" field.
func (u *OAuthGrantUpsert) SetFullAccess(v bool) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldFullAccess, v)
	return u
}

// UpdateFullAccess sets the "full_access" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateFullAccess() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldFullAccess)
	return u
}

// SetResources sets the "resources" field.
func (u *OAuthGrantUpsert) SetResources(v []schema.APIKeyResource) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldResources, v)
	return u
}

// UpdateResources sets the "resources" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateResources() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldResources)
	return u
}

// SetResource sets the "resource" field.
func (u *OAuthGrantUpsert) SetResource(v string) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldResource, v)
	return u
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateResource() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldResource)
	return u
}

// SetScope sets the "scope" field.
func (u *OAuthGrantUpsert) SetScope(v string) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateScope() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldScope)
	return u
}

// ClearScope clears the value of the "scope" field.
func (u *OAuthGrantUpsert) ClearScope() *OAuthGrantUpsert {
	u.SetNull(oauthgrant.FieldScope)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *OAuthGrantUpsert) SetLastUsedAt(v time.Time) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateLastUsedAt() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *OAuthGrantUpsert) ClearLastUsedAt() *OAuthGrantUpsert {
	u.SetNull(oauthgrant.FieldLastUsedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *OAuthGrantUpsert) SetRevokedAt(v time.Time) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateRevokedAt() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *OAuthGrantUpsert) ClearRevokedAt() *OAuthGrantUpsert {
	u.SetNull(oauthgrant.FieldRevokedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OAuthGrantUpsert) SetUserID(v uuid.UUID) *OAuthGrantUpsert {
	u.Set(oauthgrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthGrantUpsert) UpdateUserID() *OAuthGrantUpsert {
	u.SetExcluded(oauthgrant.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OAuthGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthgrant.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthGrantUpsertOne) UpdateNewValues() *OAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oauthgrant.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthgrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthGrantUpsertOne) Ignore() *OAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthGrantUpsertOne) DoNothing() *OAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthGrantCreate.OnConflict
// documentation for more info.
func (u *OAuthGrantUpsertOne) Update(set func(*OAuthGrantUpsert)) *OAuthGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthGrantUpsertOne) SetUpdatedAt(v time.Time) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateUpdatedAt() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthGrantUpsertOne) SetClientID(v string) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateClientID() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *OAuthGrantUpsertOne) SetClientName(v string) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateClientName() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientName()
	})
}

// SetClientKind sets the "client_kind" field.
func (u *OAuthGrantUpsertOne) SetClientKind(v schema.OAuthClientKind) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientKind(v)
	})
}

// UpdateClientKind sets the "client_kind" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateClientKind() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientKind()
	})
}

// SetClientURI sets the "client_uri" field.
func (u *OAuthGrantUpsertOne) SetClientURI(v string) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientURI(v)
	})
}

// UpdateClientURI sets the "client_uri" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateClientURI() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientURI()
	})
}

// ClearClientURI clears the value of the "client_uri" field.
func (u *OAuthGrantUpsertOne) ClearClientURI() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearClientURI()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthGrantUpsertOne) SetRedirectURI(v string) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateRedirectURI() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetRole sets the "role" field.
func (u *OAuthGrantUpsertOne) SetRole(v schema.PermittedAction) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateRole() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateRole()
	})
}

// SetFullAccess sets the "full_access" field.
func (u *OAuthGrantUpsertOne) SetFullAccess(v bool) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetFullAccess(v)
	})
}

// UpdateFullAccess sets the "full_access" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateFullAccess() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateFullAccess()
	})
}

// SetResources sets the "resources" field.
func (u *OAuthGrantUpsertOne) SetResources(v []schema.APIKeyResource) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetResources(v)
	})
}

// UpdateResources sets the "resources" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateResources() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateResources()
	})
}

// SetResource sets the "resource" field.
func (u *OAuthGrantUpsertOne) SetResource(v string) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateResource() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateResource()
	})
}

// SetScope sets the "scope" field.
func (u *OAuthGrantUpsertOne) SetScope(v string) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateScope() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *OAuthGrantUpsertOne) ClearScope() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearScope()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *OAuthGrantUpsertOne) SetLastUsedAt(v time.Time) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateLastUsedAt() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *OAuthGrantUpsertOne) ClearLastUsedAt() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *OAuthGrantUpsertOne) SetRevokedAt(v time.Time) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateRevokedAt() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *OAuthGrantUpsertOne) ClearRevokedAt() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearRevokedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthGrantUpsertOne) SetUserID(v uuid.UUID) *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthGrantUpsertOne) UpdateUserID() *OAuthGrantUpsertOne {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OAuthGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthGrantUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OAuthGrantUpsertOne.ID is not supported by MySQL driver. Use OAuthGrantUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthGrantUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthGrantCreateBulk is the builder for creating many OAuthGrant entities in bulk.
type OAuthGrantCreateBulk struct {
	config
	err      error
	builders []*OAuthGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthGrant entities in the database.
func (_c *OAuthGrantCreateBulk) Save(ctx context.Context) ([]*OAuthGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthGrantCreateBulk) SaveX(ctx context.Context) []*OAuthGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthGrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthGrantUpsertBulk {
	_c.conflict = opts
	return &OAuthGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthGrantCreateBulk) OnConflictColumns(columns ...string) *OAuthGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthGrantUpsertBulk{
		create: _c,
	}
}

// OAuthGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthGrant nodes.
type OAuthGrantUpsertBulk struct {
	create *OAuthGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauthgrant.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuthGrantUpsertBulk) UpdateNewValues() *OAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oauthgrant.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthgrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthGrantUpsertBulk) Ignore() *OAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthGrantUpsertBulk) DoNothing() *OAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthGrantCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthGrantUpsertBulk) Update(set func(*OAuthGrantUpsert)) *OAuthGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthGrantUpsertBulk) SetUpdatedAt(v time.Time) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateUpdatedAt() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthGrantUpsertBulk) SetClientID(v string) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateClientID() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientID()
	})
}

// SetClientName sets the "client_name" field.
func (u *OAuthGrantUpsertBulk) SetClientName(v string) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientName(v)
	})
}

// UpdateClientName sets the "client_name" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateClientName() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientName()
	})
}

// SetClientKind sets the "client_kind" field.
func (u *OAuthGrantUpsertBulk) SetClientKind(v schema.OAuthClientKind) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientKind(v)
	})
}

// UpdateClientKind sets the "client_kind" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateClientKind() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientKind()
	})
}

// SetClientURI sets the "client_uri" field.
func (u *OAuthGrantUpsertBulk) SetClientURI(v string) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetClientURI(v)
	})
}

// UpdateClientURI sets the "client_uri" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateClientURI() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateClientURI()
	})
}

// ClearClientURI clears the value of the "client_uri" field.
func (u *OAuthGrantUpsertBulk) ClearClientURI() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearClientURI()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *OAuthGrantUpsertBulk) SetRedirectURI(v string) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateRedirectURI() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetRole sets the "role" field.
func (u *OAuthGrantUpsertBulk) SetRole(v schema.PermittedAction) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateRole() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateRole()
	})
}

// SetFullAccess sets the "full_access" field.
func (u *OAuthGrantUpsertBulk) SetFullAccess(v bool) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetFullAccess(v)
	})
}

// UpdateFullAccess sets the "full_access" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateFullAccess() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateFullAccess()
	})
}

// SetResources sets the "resources" field.
func (u *OAuthGrantUpsertBulk) SetResources(v []schema.APIKeyResource) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetResources(v)
	})
}

// UpdateResources sets the "resources" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateResources() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateResources()
	})
}

// SetResource sets the "resource" field.
func (u *OAuthGrantUpsertBulk) SetResource(v string) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateResource() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateResource()
	})
}

// SetScope sets the "scope" field.
func (u *OAuthGrantUpsertBulk) SetScope(v string) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateScope() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateScope()
	})
}

// ClearScope clears the value of the "scope" field.
func (u *OAuthGrantUpsertBulk) ClearScope() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearScope()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *OAuthGrantUpsertBulk) SetLastUsedAt(v time.Time) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateLastUsedAt() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *OAuthGrantUpsertBulk) ClearLastUsedAt() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *OAuthGrantUpsertBulk) SetRevokedAt(v time.Time) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateRevokedAt() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *OAuthGrantUpsertBulk) ClearRevokedAt() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.ClearRevokedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *OAuthGrantUpsertBulk) SetUserID(v uuid.UUID) *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OAuthGrantUpsertBulk) UpdateUserID() *OAuthGrantUpsertBulk {
	return u.Update(func(s *OAuthGrantUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *OAuthGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
