// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/pvcmetadata"
)

// PVCMetadataCreate is the builder for creating a PVCMetadata entity.
type PVCMetadataCreate struct {
	config
	mutation *PVCMetadataMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PVCMetadataCreate) SetCreatedAt(v time.Time) *PVCMetadataCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PVCMetadataCreate) SetNillableCreatedAt(v *time.Time) *PVCMetadataCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PVCMetadataCreate) SetUpdatedAt(v time.Time) *PVCMetadataCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PVCMetadataCreate) SetNillableUpdatedAt(v *time.Time) *PVCMetadataCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPvcID sets the "pvc_id" field.
func (_c *PVCMetadataCreate) SetPvcID(v string) *PVCMetadataCreate {
	_c.mutation.SetPvcID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PVCMetadataCreate) SetName(v string) *PVCMetadataCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *PVCMetadataCreate) SetNillableName(v *string) *PVCMetadataCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PVCMetadataCreate) SetDescription(v string) *PVCMetadataCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PVCMetadataCreate) SetNillableDescription(v *string) *PVCMetadataCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PVCMetadataCreate) SetID(v uuid.UUID) *PVCMetadataCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PVCMetadataCreate) SetNillableID(v *uuid.UUID) *PVCMetadataCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PVCMetadataMutation object of the builder.
func (_c *PVCMetadataCreate) Mutation() *PVCMetadataMutation {
	return _c.mutation
}

// Save creates the PVCMetadata in the database.
func (_c *PVCMetadataCreate) Save(ctx context.Context) (*PVCMetadata, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PVCMetadataCreate) SaveX(ctx context.Context) *PVCMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PVCMetadataCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PVCMetadataCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PVCMetadataCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pvcmetadata.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pvcmetadata.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pvcmetadata.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PVCMetadataCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PVCMetadata.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PVCMetadata.updated_at"`)}
	}
	if _, ok := _c.mutation.PvcID(); !ok {
		return &ValidationError{Name: "pvc_id", err: errors.New(`ent: missing required field "PVCMetadata.pvc_id"`)}
	}
	return nil
}

func (_c *PVCMetadataCreate) sqlSave(ctx context.Context) (*PVCMetadata, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PVCMetadataCreate) createSpec() (*PVCMetadata, *sqlgraph.CreateSpec) {
	var (
		_node = &PVCMetadata{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pvcmetadata.Table, sqlgraph.NewFieldSpec(pvcmetadata.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pvcmetadata.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pvcmetadata.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PvcID(); ok {
		_spec.SetField(pvcmetadata.FieldPvcID, field.TypeString, value)
		_node.PvcID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(pvcmetadata.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(pvcmetadata.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PVCMetadata.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PVCMetadataUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PVCMetadataCreate) OnConflict(opts ...sql.ConflictOption) *PVCMetadataUpsertOne {
	_c.conflict = opts
	return &PVCMetadataUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PVCMetadata.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PVCMetadataCreate) OnConflictColumns(columns ...string) *PVCMetadataUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PVCMetadataUpsertOne{
		create: _c,
	}
}

type (
	// PVCMetadataUpsertOne is the builder for "upsert"-ing
	//  one PVCMetadata node.
	PVCMetadataUpsertOne struct {
		create *PVCMetadataCreate
	}

	// PVCMetadataUpsert is the "OnConflict" setter.
	PVCMetadataUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PVCMetadataUpsert) SetUpdatedAt(v time.Time) *PVCMetadataUpsert {
	u.Set(pvcmetadata.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PVCMetadataUpsert) UpdateUpdatedAt() *PVCMetadataUpsert {
	u.SetExcluded(pvcmetadata.FieldUpdatedAt)
	return u
}

// SetPvcID sets the "pvc_id" field.
func (u *PVCMetadataUpsert) SetPvcID(v string) *PVCMetadataUpsert {
	u.Set(pvcmetadata.FieldPvcID, v)
	return u
}

// UpdatePvcID sets the "pvc_id" field to the value that was provided on create.
func (u *PVCMetadataUpsert) UpdatePvcID() *PVCMetadataUpsert {
	u.SetExcluded(pvcmetadata.FieldPvcID)
	return u
}

// SetName sets the "name" field.
func (u *PVCMetadataUpsert) SetName(v string) *PVCMetadataUpsert {
	u.Set(pvcmetadata.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PVCMetadataUpsert) UpdateName() *PVCMetadataUpsert {
	u.SetExcluded(pvcmetadata.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *PVCMetadataUpsert) ClearName() *PVCMetadataUpsert {
	u.SetNull(pvcmetadata.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *PVCMetadataUpsert) SetDescription(v string) *PVCMetadataUpsert {
	u.Set(pvcmetadata.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PVCMetadataUpsert) UpdateDescription() *PVCMetadataUpsert {
	u.SetExcluded(pvcmetadata.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PVCMetadataUpsert) ClearDescription() *PVCMetadataUpsert {
	u.SetNull(pvcmetadata.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PVCMetadata.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pvcmetadata.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PVCMetadataUpsertOne) UpdateNewValues() *PVCMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pvcmetadata.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pvcmetadata.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PVCMetadata.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PVCMetadataUpsertOne) Ignore() *PVCMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PVCMetadataUpsertOne) DoNothing() *PVCMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PVCMetadataCreate.OnConflict
// documentation for more info.
func (u *PVCMetadataUpsertOne) Update(set func(*PVCMetadataUpsert)) *PVCMetadataUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PVCMetadataUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PVCMetadataUpsertOne) SetUpdatedAt(v time.Time) *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PVCMetadataUpsertOne) UpdateUpdatedAt() *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPvcID sets the "pvc_id" field.
func (u *PVCMetadataUpsertOne) SetPvcID(v string) *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetPvcID(v)
	})
}

// UpdatePvcID sets the "pvc_id" field to the value that was provided on create.
func (u *PVCMetadataUpsertOne) UpdatePvcID() *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdatePvcID()
	})
}

// SetName sets the "name" field.
func (u *PVCMetadataUpsertOne) SetName(v string) *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PVCMetadataUpsertOne) UpdateName() *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *PVCMetadataUpsertOne) ClearName() *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *PVCMetadataUpsertOne) SetDescription(v string) *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PVCMetadataUpsertOne) UpdateDescription() *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PVCMetadataUpsertOne) ClearDescription() *PVCMetadataUpsertOne {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *PVCMetadataUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PVCMetadataCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PVCMetadataUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PVCMetadataUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PVCMetadataUpsertOne.ID is not supported by MySQL driver. Use PVCMetadataUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PVCMetadataUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PVCMetadataCreateBulk is the builder for creating many PVCMetadata entities in bulk.
type PVCMetadataCreateBulk struct {
	config
	err      error
	builders []*PVCMetadataCreate
	conflict []sql.ConflictOption
}

// Save creates the PVCMetadata entities in the database.
func (_c *PVCMetadataCreateBulk) Save(ctx context.Context) ([]*PVCMetadata, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PVCMetadata, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PVCMetadataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PVCMetadataCreateBulk) SaveX(ctx context.Context) []*PVCMetadata {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PVCMetadataCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PVCMetadataCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PVCMetadata.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PVCMetadataUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PVCMetadataCreateBulk) OnConflict(opts ...sql.ConflictOption) *PVCMetadataUpsertBulk {
	_c.conflict = opts
	return &PVCMetadataUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PVCMetadata.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PVCMetadataCreateBulk) OnConflictColumns(columns ...string) *PVCMetadataUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PVCMetadataUpsertBulk{
		create: _c,
	}
}

// PVCMetadataUpsertBulk is the builder for "upsert"-ing
// a bulk of PVCMetadata nodes.
type PVCMetadataUpsertBulk struct {
	create *PVCMetadataCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PVCMetadata.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pvcmetadata.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PVCMetadataUpsertBulk) UpdateNewValues() *PVCMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pvcmetadata.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pvcmetadata.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PVCMetadata.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PVCMetadataUpsertBulk) Ignore() *PVCMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PVCMetadataUpsertBulk) DoNothing() *PVCMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PVCMetadataCreateBulk.OnConflict
// documentation for more info.
func (u *PVCMetadataUpsertBulk) Update(set func(*PVCMetadataUpsert)) *PVCMetadataUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PVCMetadataUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PVCMetadataUpsertBulk) SetUpdatedAt(v time.Time) *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PVCMetadataUpsertBulk) UpdateUpdatedAt() *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPvcID sets the "pvc_id" field.
func (u *PVCMetadataUpsertBulk) SetPvcID(v string) *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetPvcID(v)
	})
}

// UpdatePvcID sets the "pvc_id" field to the value that was provided on create.
func (u *PVCMetadataUpsertBulk) UpdatePvcID() *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdatePvcID()
	})
}

// SetName sets the "name" field.
func (u *PVCMetadataUpsertBulk) SetName(v string) *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PVCMetadataUpsertBulk) UpdateName() *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *PVCMetadataUpsertBulk) ClearName() *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *PVCMetadataUpsertBulk) SetDescription(v string) *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PVCMetadataUpsertBulk) UpdateDescription() *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PVCMetadataUpsertBulk) ClearDescription() *PVCMetadataUpsertBulk {
	return u.Update(func(s *PVCMetadataUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *PVCMetadataUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PVCMetadataCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PVCMetadataCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PVCMetadataUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
