// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/predicate"
	"github.com/unbindapp/unbind-api/ent/s3"
	"github.com/unbindapp/unbind-api/ent/schema"
	"github.com/unbindapp/unbind-api/ent/service"
	"github.com/unbindapp/unbind-api/ent/serviceconfig"
	"github.com/unbindapp/unbind-api/internal/sourceanalyzer/enum"
)

// ServiceConfigUpdate is the builder for updating ServiceConfig entities.
type ServiceConfigUpdate struct {
	config
	hooks     []Hook
	mutation  *ServiceConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ServiceConfigUpdate builder.
func (_u *ServiceConfigUpdate) Where(ps ...predicate.ServiceConfig) *ServiceConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceConfigUpdate) SetUpdatedAt(v time.Time) *ServiceConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *ServiceConfigUpdate) SetServiceID(v uuid.UUID) *ServiceConfigUpdate {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableServiceID(v *uuid.UUID) *ServiceConfigUpdate {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// SetBuilder sets the "builder" field.
func (_u *ServiceConfigUpdate) SetBuilder(v schema.ServiceBuilder) *ServiceConfigUpdate {
	_u.mutation.SetBuilder(v)
	return _u
}

// SetNillableBuilder sets the "builder" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableBuilder(v *schema.ServiceBuilder) *ServiceConfigUpdate {
	if v != nil {
		_u.SetBuilder(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ServiceConfigUpdate) SetIcon(v string) *ServiceConfigUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableIcon(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetDockerBuilderDockerfilePath sets the "docker_builder_dockerfile_path" field.
func (_u *ServiceConfigUpdate) SetDockerBuilderDockerfilePath(v string) *ServiceConfigUpdate {
	_u.mutation.SetDockerBuilderDockerfilePath(v)
	return _u
}

// SetNillableDockerBuilderDockerfilePath sets the "docker_builder_dockerfile_path" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableDockerBuilderDockerfilePath(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetDockerBuilderDockerfilePath(*v)
	}
	return _u
}

// ClearDockerBuilderDockerfilePath clears the value of the "docker_builder_dockerfile_path" field.
func (_u *ServiceConfigUpdate) ClearDockerBuilderDockerfilePath() *ServiceConfigUpdate {
	_u.mutation.ClearDockerBuilderDockerfilePath()
	return _u
}

// SetDockerBuilderBuildContext sets the "docker_builder_build_context" field.
func (_u *ServiceConfigUpdate) SetDockerBuilderBuildContext(v string) *ServiceConfigUpdate {
	_u.mutation.SetDockerBuilderBuildContext(v)
	return _u
}

// SetNillableDockerBuilderBuildContext sets the "docker_builder_build_context" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableDockerBuilderBuildContext(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetDockerBuilderBuildContext(*v)
	}
	return _u
}

// ClearDockerBuilderBuildContext clears the value of the "docker_builder_build_context" field.
func (_u *ServiceConfigUpdate) ClearDockerBuilderBuildContext() *ServiceConfigUpdate {
	_u.mutation.ClearDockerBuilderBuildContext()
	return _u
}

// SetRailpackProvider sets the "railpack_provider" field.
func (_u *ServiceConfigUpdate) SetRailpackProvider(v enum.Provider) *ServiceConfigUpdate {
	_u.mutation.SetRailpackProvider(v)
	return _u
}

// SetNillableRailpackProvider sets the "railpack_provider" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableRailpackProvider(v *enum.Provider) *ServiceConfigUpdate {
	if v != nil {
		_u.SetRailpackProvider(*v)
	}
	return _u
}

// ClearRailpackProvider clears the value of the "railpack_provider" field.
func (_u *ServiceConfigUpdate) ClearRailpackProvider() *ServiceConfigUpdate {
	_u.mutation.ClearRailpackProvider()
	return _u
}

// SetRailpackFramework sets the "railpack_framework" field.
func (_u *ServiceConfigUpdate) SetRailpackFramework(v enum.Framework) *ServiceConfigUpdate {
	_u.mutation.SetRailpackFramework(v)
	return _u
}

// SetNillableRailpackFramework sets the "railpack_framework" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableRailpackFramework(v *enum.Framework) *ServiceConfigUpdate {
	if v != nil {
		_u.SetRailpackFramework(*v)
	}
	return _u
}

// ClearRailpackFramework clears the value of the "railpack_framework" field.
func (_u *ServiceConfigUpdate) ClearRailpackFramework() *ServiceConfigUpdate {
	_u.mutation.ClearRailpackFramework()
	return _u
}

// SetGitBranch sets the "git_branch" field.
func (_u *ServiceConfigUpdate) SetGitBranch(v string) *ServiceConfigUpdate {
	_u.mutation.SetGitBranch(v)
	return _u
}

// SetNillableGitBranch sets the "git_branch" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableGitBranch(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetGitBranch(*v)
	}
	return _u
}

// ClearGitBranch clears the value of the "git_branch" field.
func (_u *ServiceConfigUpdate) ClearGitBranch() *ServiceConfigUpdate {
	_u.mutation.ClearGitBranch()
	return _u
}

// SetGitTag sets the "git_tag" field.
func (_u *ServiceConfigUpdate) SetGitTag(v string) *ServiceConfigUpdate {
	_u.mutation.SetGitTag(v)
	return _u
}

// SetNillableGitTag sets the "git_tag" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableGitTag(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetGitTag(*v)
	}
	return _u
}

// ClearGitTag clears the value of the "git_tag" field.
func (_u *ServiceConfigUpdate) ClearGitTag() *ServiceConfigUpdate {
	_u.mutation.ClearGitTag()
	return _u
}

// SetHosts sets the "hosts" field.
func (_u *ServiceConfigUpdate) SetHosts(v []schema.HostSpec) *ServiceConfigUpdate {
	_u.mutation.SetHosts(v)
	return _u
}

// AppendHosts appends value to the "hosts" field.
func (_u *ServiceConfigUpdate) AppendHosts(v []schema.HostSpec) *ServiceConfigUpdate {
	_u.mutation.AppendHosts(v)
	return _u
}

// ClearHosts clears the value of the "hosts" field.
func (_u *ServiceConfigUpdate) ClearHosts() *ServiceConfigUpdate {
	_u.mutation.ClearHosts()
	return _u
}

// SetPorts sets the "ports" field.
func (_u *ServiceConfigUpdate) SetPorts(v []schema.PortSpec) *ServiceConfigUpdate {
	_u.mutation.SetPorts(v)
	return _u
}

// AppendPorts appends value to the "ports" field.
func (_u *ServiceConfigUpdate) AppendPorts(v []schema.PortSpec) *ServiceConfigUpdate {
	_u.mutation.AppendPorts(v)
	return _u
}

// ClearPorts clears the value of the "ports" field.
func (_u *ServiceConfigUpdate) ClearPorts() *ServiceConfigUpdate {
	_u.mutation.ClearPorts()
	return _u
}

// SetReplicas sets the "replicas" field.
func (_u *ServiceConfigUpdate) SetReplicas(v int32) *ServiceConfigUpdate {
	_u.mutation.ResetReplicas()
	_u.mutation.SetReplicas(v)
	return _u
}

// SetNillableReplicas sets the "replicas" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableReplicas(v *int32) *ServiceConfigUpdate {
	if v != nil {
		_u.SetReplicas(*v)
	}
	return _u
}

// AddReplicas adds value to the "replicas" field.
func (_u *ServiceConfigUpdate) AddReplicas(v int32) *ServiceConfigUpdate {
	_u.mutation.AddReplicas(v)
	return _u
}

// SetAutoDeploy sets the "auto_deploy" field.
func (_u *ServiceConfigUpdate) SetAutoDeploy(v bool) *ServiceConfigUpdate {
	_u.mutation.SetAutoDeploy(v)
	return _u
}

// SetNillableAutoDeploy sets the "auto_deploy" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableAutoDeploy(v *bool) *ServiceConfigUpdate {
	if v != nil {
		_u.SetAutoDeploy(*v)
	}
	return _u
}

// SetRailpackBuilderInstallCommand sets the "railpack_builder_install_command" field.
func (_u *ServiceConfigUpdate) SetRailpackBuilderInstallCommand(v string) *ServiceConfigUpdate {
	_u.mutation.SetRailpackBuilderInstallCommand(v)
	return _u
}

// SetNillableRailpackBuilderInstallCommand sets the "railpack_builder_install_command" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableRailpackBuilderInstallCommand(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetRailpackBuilderInstallCommand(*v)
	}
	return _u
}

// ClearRailpackBuilderInstallCommand clears the value of the "railpack_builder_install_command" field.
func (_u *ServiceConfigUpdate) ClearRailpackBuilderInstallCommand() *ServiceConfigUpdate {
	_u.mutation.ClearRailpackBuilderInstallCommand()
	return _u
}

// SetRailpackBuilderBuildCommand sets the "railpack_builder_build_command" field.
func (_u *ServiceConfigUpdate) SetRailpackBuilderBuildCommand(v string) *ServiceConfigUpdate {
	_u.mutation.SetRailpackBuilderBuildCommand(v)
	return _u
}

// SetNillableRailpackBuilderBuildCommand sets the "railpack_builder_build_command" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableRailpackBuilderBuildCommand(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetRailpackBuilderBuildCommand(*v)
	}
	return _u
}

// ClearRailpackBuilderBuildCommand clears the value of the "railpack_builder_build_command" field.
func (_u *ServiceConfigUpdate) ClearRailpackBuilderBuildCommand() *ServiceConfigUpdate {
	_u.mutation.ClearRailpackBuilderBuildCommand()
	return _u
}

// SetRunCommand sets the "run_command" field.
func (_u *ServiceConfigUpdate) SetRunCommand(v string) *ServiceConfigUpdate {
	_u.mutation.SetRunCommand(v)
	return _u
}

// SetNillableRunCommand sets the "run_command" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableRunCommand(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetRunCommand(*v)
	}
	return _u
}

// ClearRunCommand clears the value of the "run_command" field.
func (_u *ServiceConfigUpdate) ClearRunCommand() *ServiceConfigUpdate {
	_u.mutation.ClearRunCommand()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ServiceConfigUpdate) SetIsPublic(v bool) *ServiceConfigUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableIsPublic(v *bool) *ServiceConfigUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ServiceConfigUpdate) SetImage(v string) *ServiceConfigUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableImage(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *ServiceConfigUpdate) ClearImage() *ServiceConfigUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetDefinitionVersion sets the "definition_version" field.
func (_u *ServiceConfigUpdate) SetDefinitionVersion(v string) *ServiceConfigUpdate {
	_u.mutation.SetDefinitionVersion(v)
	return _u
}

// SetNillableDefinitionVersion sets the "definition_version" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableDefinitionVersion(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetDefinitionVersion(*v)
	}
	return _u
}

// ClearDefinitionVersion clears the value of the "definition_version" field.
func (_u *ServiceConfigUpdate) ClearDefinitionVersion() *ServiceConfigUpdate {
	_u.mutation.ClearDefinitionVersion()
	return _u
}

// SetDatabaseConfig sets the "database_config" field.
func (_u *ServiceConfigUpdate) SetDatabaseConfig(v *schema.DatabaseConfig) *ServiceConfigUpdate {
	_u.mutation.SetDatabaseConfig(v)
	return _u
}

// ClearDatabaseConfig clears the value of the "database_config" field.
func (_u *ServiceConfigUpdate) ClearDatabaseConfig() *ServiceConfigUpdate {
	_u.mutation.ClearDatabaseConfig()
	return _u
}

// SetS3BackupSourceID sets the "s3_backup_source_id" field.
func (_u *ServiceConfigUpdate) SetS3BackupSourceID(v uuid.UUID) *ServiceConfigUpdate {
	_u.mutation.SetS3BackupSourceID(v)
	return _u
}

// SetNillableS3BackupSourceID sets the "s3_backup_source_id" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableS3BackupSourceID(v *uuid.UUID) *ServiceConfigUpdate {
	if v != nil {
		_u.SetS3BackupSourceID(*v)
	}
	return _u
}

// ClearS3BackupSourceID clears the value of the "s3_backup_source_id" field.
func (_u *ServiceConfigUpdate) ClearS3BackupSourceID() *ServiceConfigUpdate {
	_u.mutation.ClearS3BackupSourceID()
	return _u
}

// SetS3BackupBucket sets the "s3_backup_bucket" field.
func (_u *ServiceConfigUpdate) SetS3BackupBucket(v string) *ServiceConfigUpdate {
	_u.mutation.SetS3BackupBucket(v)
	return _u
}

// SetNillableS3BackupBucket sets the "s3_backup_bucket" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableS3BackupBucket(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetS3BackupBucket(*v)
	}
	return _u
}

// ClearS3BackupBucket clears the value of the "s3_backup_bucket" field.
func (_u *ServiceConfigUpdate) ClearS3BackupBucket() *ServiceConfigUpdate {
	_u.mutation.ClearS3BackupBucket()
	return _u
}

// SetBackupSchedule sets the "backup_schedule" field.
func (_u *ServiceConfigUpdate) SetBackupSchedule(v string) *ServiceConfigUpdate {
	_u.mutation.SetBackupSchedule(v)
	return _u
}

// SetNillableBackupSchedule sets the "backup_schedule" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableBackupSchedule(v *string) *ServiceConfigUpdate {
	if v != nil {
		_u.SetBackupSchedule(*v)
	}
	return _u
}

// SetBackupRetentionCount sets the "backup_retention_count" field.
func (_u *ServiceConfigUpdate) SetBackupRetentionCount(v int) *ServiceConfigUpdate {
	_u.mutation.ResetBackupRetentionCount()
	_u.mutation.SetBackupRetentionCount(v)
	return _u
}

// SetNillableBackupRetentionCount sets the "backup_retention_count" field if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableBackupRetentionCount(v *int) *ServiceConfigUpdate {
	if v != nil {
		_u.SetBackupRetentionCount(*v)
	}
	return _u
}

// AddBackupRetentionCount adds value to the "backup_retention_count" field.
func (_u *ServiceConfigUpdate) AddBackupRetentionCount(v int) *ServiceConfigUpdate {
	_u.mutation.AddBackupRetentionCount(v)
	return _u
}

// SetVolumes sets the "volumes" field.
func (_u *ServiceConfigUpdate) SetVolumes(v []schema.ServiceVolume) *ServiceConfigUpdate {
	_u.mutation.SetVolumes(v)
	return _u
}

// AppendVolumes appends value to the "volumes" field.
func (_u *ServiceConfigUpdate) AppendVolumes(v []schema.ServiceVolume) *ServiceConfigUpdate {
	_u.mutation.AppendVolumes(v)
	return _u
}

// ClearVolumes clears the value of the "volumes" field.
func (_u *ServiceConfigUpdate) ClearVolumes() *ServiceConfigUpdate {
	_u.mutation.ClearVolumes()
	return _u
}

// SetSecurityContext sets the "security_context" field.
func (_u *ServiceConfigUpdate) SetSecurityContext(v *schema.SecurityContext) *ServiceConfigUpdate {
	_u.mutation.SetSecurityContext(v)
	return _u
}

// ClearSecurityContext clears the value of the "security_context" field.
func (_u *ServiceConfigUpdate) ClearSecurityContext() *ServiceConfigUpdate {
	_u.mutation.ClearSecurityContext()
	return _u
}

// SetHealthCheck sets the "health_check" field.
func (_u *ServiceConfigUpdate) SetHealthCheck(v *schema.HealthCheck) *ServiceConfigUpdate {
	_u.mutation.SetHealthCheck(v)
	return _u
}

// ClearHealthCheck clears the value of the "health_check" field.
func (_u *ServiceConfigUpdate) ClearHealthCheck() *ServiceConfigUpdate {
	_u.mutation.ClearHealthCheck()
	return _u
}

// SetVariableMounts sets the "variable_mounts" field.
func (_u *ServiceConfigUpdate) SetVariableMounts(v []*schema.VariableMount) *ServiceConfigUpdate {
	_u.mutation.SetVariableMounts(v)
	return _u
}

// AppendVariableMounts appends value to the "variable_mounts" field.
func (_u *ServiceConfigUpdate) AppendVariableMounts(v []*schema.VariableMount) *ServiceConfigUpdate {
	_u.mutation.AppendVariableMounts(v)
	return _u
}

// ClearVariableMounts clears the value of the "variable_mounts" field.
func (_u *ServiceConfigUpdate) ClearVariableMounts() *ServiceConfigUpdate {
	_u.mutation.ClearVariableMounts()
	return _u
}

// SetProtectedVariables sets the "protected_variables" field.
func (_u *ServiceConfigUpdate) SetProtectedVariables(v []string) *ServiceConfigUpdate {
	_u.mutation.SetProtectedVariables(v)
	return _u
}

// AppendProtectedVariables appends value to the "protected_variables" field.
func (_u *ServiceConfigUpdate) AppendProtectedVariables(v []string) *ServiceConfigUpdate {
	_u.mutation.AppendProtectedVariables(v)
	return _u
}

// ClearProtectedVariables clears the value of the "protected_variables" field.
func (_u *ServiceConfigUpdate) ClearProtectedVariables() *ServiceConfigUpdate {
	_u.mutation.ClearProtectedVariables()
	return _u
}

// SetInitContainers sets the "init_containers" field.
func (_u *ServiceConfigUpdate) SetInitContainers(v []*schema.InitContainer) *ServiceConfigUpdate {
	_u.mutation.SetInitContainers(v)
	return _u
}

// AppendInitContainers appends value to the "init_containers" field.
func (_u *ServiceConfigUpdate) AppendInitContainers(v []*schema.InitContainer) *ServiceConfigUpdate {
	_u.mutation.AppendInitContainers(v)
	return _u
}

// ClearInitContainers clears the value of the "init_containers" field.
func (_u *ServiceConfigUpdate) ClearInitContainers() *ServiceConfigUpdate {
	_u.mutation.ClearInitContainers()
	return _u
}

// SetResources sets the "resources" field.
func (_u *ServiceConfigUpdate) SetResources(v *schema.Resources) *ServiceConfigUpdate {
	_u.mutation.SetResources(v)
	return _u
}

// ClearResources clears the value of the "resources" field.
func (_u *ServiceConfigUpdate) ClearResources() *ServiceConfigUpdate {
	_u.mutation.ClearResources()
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *ServiceConfigUpdate) SetService(v *Service) *ServiceConfigUpdate {
	return _u.SetServiceID(v.ID)
}

// SetS3BackupSourcesID sets the "s3_backup_sources" edge to the S3 entity by ID.
func (_u *ServiceConfigUpdate) SetS3BackupSourcesID(id uuid.UUID) *ServiceConfigUpdate {
	_u.mutation.SetS3BackupSourcesID(id)
	return _u
}

// SetNillableS3BackupSourcesID sets the "s3_backup_sources" edge to the S3 entity by ID if the given value is not nil.
func (_u *ServiceConfigUpdate) SetNillableS3BackupSourcesID(id *uuid.UUID) *ServiceConfigUpdate {
	if id != nil {
		_u = _u.SetS3BackupSourcesID(*id)
	}
	return _u
}

// SetS3BackupSources sets the "s3_backup_sources" edge to the S3 entity.
func (_u *ServiceConfigUpdate) SetS3BackupSources(v *S3) *ServiceConfigUpdate {
	return _u.SetS3BackupSourcesID(v.ID)
}

// Mutation returns the ServiceConfigMutation object of the builder.
func (_u *ServiceConfigUpdate) Mutation() *ServiceConfigMutation {
	return _u.mutation
}

// ClearService clears the "service" edge to the Service entity.
func (_u *ServiceConfigUpdate) ClearService() *ServiceConfigUpdate {
	_u.mutation.ClearService()
	return _u
}

// ClearS3BackupSources clears the "s3_backup_sources" edge to the S3 entity.
func (_u *ServiceConfigUpdate) ClearS3BackupSources() *ServiceConfigUpdate {
	_u.mutation.ClearS3BackupSources()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceConfigUpdate) check() error {
	if v, ok := _u.mutation.Builder(); ok {
		if err := serviceconfig.BuilderValidator(v); err != nil {
			return &ValidationError{Name: "builder", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.builder": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RailpackProvider(); ok {
		if err := serviceconfig.RailpackProviderValidator(v); err != nil {
			return &ValidationError{Name: "railpack_provider", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.railpack_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RailpackFramework(); ok {
		if err := serviceconfig.RailpackFrameworkValidator(v); err != nil {
			return &ValidationError{Name: "railpack_framework", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.railpack_framework": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthCheck(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "health_check", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.health_check": %w`, err)}
		}
	}
	if _u.mutation.ServiceCleared() && len(_u.mutation.ServiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceConfig.service"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ServiceConfigUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ServiceConfigUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ServiceConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceconfig.Table, serviceconfig.Columns, sqlgraph.NewFieldSpec(serviceconfig.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Builder(); ok {
		_spec.SetField(serviceconfig.FieldBuilder, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(serviceconfig.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.DockerBuilderDockerfilePath(); ok {
		_spec.SetField(serviceconfig.FieldDockerBuilderDockerfilePath, field.TypeString, value)
	}
	if _u.mutation.DockerBuilderDockerfilePathCleared() {
		_spec.ClearField(serviceconfig.FieldDockerBuilderDockerfilePath, field.TypeString)
	}
	if value, ok := _u.mutation.DockerBuilderBuildContext(); ok {
		_spec.SetField(serviceconfig.FieldDockerBuilderBuildContext, field.TypeString, value)
	}
	if _u.mutation.DockerBuilderBuildContextCleared() {
		_spec.ClearField(serviceconfig.FieldDockerBuilderBuildContext, field.TypeString)
	}
	if value, ok := _u.mutation.RailpackProvider(); ok {
		_spec.SetField(serviceconfig.FieldRailpackProvider, field.TypeEnum, value)
	}
	if _u.mutation.RailpackProviderCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackProvider, field.TypeEnum)
	}
	if value, ok := _u.mutation.RailpackFramework(); ok {
		_spec.SetField(serviceconfig.FieldRailpackFramework, field.TypeEnum, value)
	}
	if _u.mutation.RailpackFrameworkCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackFramework, field.TypeEnum)
	}
	if value, ok := _u.mutation.GitBranch(); ok {
		_spec.SetField(serviceconfig.FieldGitBranch, field.TypeString, value)
	}
	if _u.mutation.GitBranchCleared() {
		_spec.ClearField(serviceconfig.FieldGitBranch, field.TypeString)
	}
	if value, ok := _u.mutation.GitTag(); ok {
		_spec.SetField(serviceconfig.FieldGitTag, field.TypeString, value)
	}
	if _u.mutation.GitTagCleared() {
		_spec.ClearField(serviceconfig.FieldGitTag, field.TypeString)
	}
	if value, ok := _u.mutation.Hosts(); ok {
		_spec.SetField(serviceconfig.FieldHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldHosts, value)
		})
	}
	if _u.mutation.HostsCleared() {
		_spec.ClearField(serviceconfig.FieldHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.Ports(); ok {
		_spec.SetField(serviceconfig.FieldPorts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPorts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldPorts, value)
		})
	}
	if _u.mutation.PortsCleared() {
		_spec.ClearField(serviceconfig.FieldPorts, field.TypeJSON)
	}
	if value, ok := _u.mutation.Replicas(); ok {
		_spec.SetField(serviceconfig.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedReplicas(); ok {
		_spec.AddField(serviceconfig.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AutoDeploy(); ok {
		_spec.SetField(serviceconfig.FieldAutoDeploy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RailpackBuilderInstallCommand(); ok {
		_spec.SetField(serviceconfig.FieldRailpackBuilderInstallCommand, field.TypeString, value)
	}
	if _u.mutation.RailpackBuilderInstallCommandCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackBuilderInstallCommand, field.TypeString)
	}
	if value, ok := _u.mutation.RailpackBuilderBuildCommand(); ok {
		_spec.SetField(serviceconfig.FieldRailpackBuilderBuildCommand, field.TypeString, value)
	}
	if _u.mutation.RailpackBuilderBuildCommandCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackBuilderBuildCommand, field.TypeString)
	}
	if value, ok := _u.mutation.RunCommand(); ok {
		_spec.SetField(serviceconfig.FieldRunCommand, field.TypeString, value)
	}
	if _u.mutation.RunCommandCleared() {
		_spec.ClearField(serviceconfig.FieldRunCommand, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(serviceconfig.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(serviceconfig.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(serviceconfig.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.DefinitionVersion(); ok {
		_spec.SetField(serviceconfig.FieldDefinitionVersion, field.TypeString, value)
	}
	if _u.mutation.DefinitionVersionCleared() {
		_spec.ClearField(serviceconfig.FieldDefinitionVersion, field.TypeString)
	}
	if value, ok := _u.mutation.DatabaseConfig(); ok {
		_spec.SetField(serviceconfig.FieldDatabaseConfig, field.TypeJSON, value)
	}
	if _u.mutation.DatabaseConfigCleared() {
		_spec.ClearField(serviceconfig.FieldDatabaseConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.S3BackupBucket(); ok {
		_spec.SetField(serviceconfig.FieldS3BackupBucket, field.TypeString, value)
	}
	if _u.mutation.S3BackupBucketCleared() {
		_spec.ClearField(serviceconfig.FieldS3BackupBucket, field.TypeString)
	}
	if value, ok := _u.mutation.BackupSchedule(); ok {
		_spec.SetField(serviceconfig.FieldBackupSchedule, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupRetentionCount(); ok {
		_spec.SetField(serviceconfig.FieldBackupRetentionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBackupRetentionCount(); ok {
		_spec.AddField(serviceconfig.FieldBackupRetentionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Volumes(); ok {
		_spec.SetField(serviceconfig.FieldVolumes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVolumes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldVolumes, value)
		})
	}
	if _u.mutation.VolumesCleared() {
		_spec.ClearField(serviceconfig.FieldVolumes, field.TypeJSON)
	}
	if value, ok := _u.mutation.SecurityContext(); ok {
		_spec.SetField(serviceconfig.FieldSecurityContext, field.TypeJSON, value)
	}
	if _u.mutation.SecurityContextCleared() {
		_spec.ClearField(serviceconfig.FieldSecurityContext, field.TypeJSON)
	}
	if value, ok := _u.mutation.HealthCheck(); ok {
		_spec.SetField(serviceconfig.FieldHealthCheck, field.TypeJSON, value)
	}
	if _u.mutation.HealthCheckCleared() {
		_spec.ClearField(serviceconfig.FieldHealthCheck, field.TypeJSON)
	}
	if value, ok := _u.mutation.VariableMounts(); ok {
		_spec.SetField(serviceconfig.FieldVariableMounts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariableMounts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldVariableMounts, value)
		})
	}
	if _u.mutation.VariableMountsCleared() {
		_spec.ClearField(serviceconfig.FieldVariableMounts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProtectedVariables(); ok {
		_spec.SetField(serviceconfig.FieldProtectedVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProtectedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldProtectedVariables, value)
		})
	}
	if _u.mutation.ProtectedVariablesCleared() {
		_spec.ClearField(serviceconfig.FieldProtectedVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.InitContainers(); ok {
		_spec.SetField(serviceconfig.FieldInitContainers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInitContainers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldInitContainers, value)
		})
	}
	if _u.mutation.InitContainersCleared() {
		_spec.ClearField(serviceconfig.FieldInitContainers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Resources(); ok {
		_spec.SetField(serviceconfig.FieldResources, field.TypeJSON, value)
	}
	if _u.mutation.ResourcesCleared() {
		_spec.ClearField(serviceconfig.FieldResources, field.TypeJSON)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   serviceconfig.ServiceTable,
			Columns: []string{serviceconfig.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   serviceconfig.ServiceTable,
			Columns: []string{serviceconfig.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.S3BackupSourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceconfig.S3BackupSourcesTable,
			Columns: []string{serviceconfig.S3BackupSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.S3BackupSourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceconfig.S3BackupSourcesTable,
			Columns: []string{serviceconfig.S3BackupSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceConfigUpdateOne is the builder for updating a single ServiceConfig entity.
type ServiceConfigUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ServiceConfigMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceConfigUpdateOne) SetUpdatedAt(v time.Time) *ServiceConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *ServiceConfigUpdateOne) SetServiceID(v uuid.UUID) *ServiceConfigUpdateOne {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableServiceID(v *uuid.UUID) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// SetBuilder sets the "builder" field.
func (_u *ServiceConfigUpdateOne) SetBuilder(v schema.ServiceBuilder) *ServiceConfigUpdateOne {
	_u.mutation.SetBuilder(v)
	return _u
}

// SetNillableBuilder sets the "builder" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableBuilder(v *schema.ServiceBuilder) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetBuilder(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ServiceConfigUpdateOne) SetIcon(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableIcon(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetDockerBuilderDockerfilePath sets the "docker_builder_dockerfile_path" field.
func (_u *ServiceConfigUpdateOne) SetDockerBuilderDockerfilePath(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetDockerBuilderDockerfilePath(v)
	return _u
}

// SetNillableDockerBuilderDockerfilePath sets the "docker_builder_dockerfile_path" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableDockerBuilderDockerfilePath(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetDockerBuilderDockerfilePath(*v)
	}
	return _u
}

// ClearDockerBuilderDockerfilePath clears the value of the "docker_builder_dockerfile_path" field.
func (_u *ServiceConfigUpdateOne) ClearDockerBuilderDockerfilePath() *ServiceConfigUpdateOne {
	_u.mutation.ClearDockerBuilderDockerfilePath()
	return _u
}

// SetDockerBuilderBuildContext sets the "docker_builder_build_context" field.
func (_u *ServiceConfigUpdateOne) SetDockerBuilderBuildContext(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetDockerBuilderBuildContext(v)
	return _u
}

// SetNillableDockerBuilderBuildContext sets the "docker_builder_build_context" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableDockerBuilderBuildContext(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetDockerBuilderBuildContext(*v)
	}
	return _u
}

// ClearDockerBuilderBuildContext clears the value of the "docker_builder_build_context" field.
func (_u *ServiceConfigUpdateOne) ClearDockerBuilderBuildContext() *ServiceConfigUpdateOne {
	_u.mutation.ClearDockerBuilderBuildContext()
	return _u
}

// SetRailpackProvider sets the "railpack_provider" field.
func (_u *ServiceConfigUpdateOne) SetRailpackProvider(v enum.Provider) *ServiceConfigUpdateOne {
	_u.mutation.SetRailpackProvider(v)
	return _u
}

// SetNillableRailpackProvider sets the "railpack_provider" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableRailpackProvider(v *enum.Provider) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetRailpackProvider(*v)
	}
	return _u
}

// ClearRailpackProvider clears the value of the "railpack_provider" field.
func (_u *ServiceConfigUpdateOne) ClearRailpackProvider() *ServiceConfigUpdateOne {
	_u.mutation.ClearRailpackProvider()
	return _u
}

// SetRailpackFramework sets the "railpack_framework" field.
func (_u *ServiceConfigUpdateOne) SetRailpackFramework(v enum.Framework) *ServiceConfigUpdateOne {
	_u.mutation.SetRailpackFramework(v)
	return _u
}

// SetNillableRailpackFramework sets the "railpack_framework" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableRailpackFramework(v *enum.Framework) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetRailpackFramework(*v)
	}
	return _u
}

// ClearRailpackFramework clears the value of the "railpack_framework" field.
func (_u *ServiceConfigUpdateOne) ClearRailpackFramework() *ServiceConfigUpdateOne {
	_u.mutation.ClearRailpackFramework()
	return _u
}

// SetGitBranch sets the "git_branch" field.
func (_u *ServiceConfigUpdateOne) SetGitBranch(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetGitBranch(v)
	return _u
}

// SetNillableGitBranch sets the "git_branch" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableGitBranch(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetGitBranch(*v)
	}
	return _u
}

// ClearGitBranch clears the value of the "git_branch" field.
func (_u *ServiceConfigUpdateOne) ClearGitBranch() *ServiceConfigUpdateOne {
	_u.mutation.ClearGitBranch()
	return _u
}

// SetGitTag sets the "git_tag" field.
func (_u *ServiceConfigUpdateOne) SetGitTag(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetGitTag(v)
	return _u
}

// SetNillableGitTag sets the "git_tag" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableGitTag(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetGitTag(*v)
	}
	return _u
}

// ClearGitTag clears the value of the "git_tag" field.
func (_u *ServiceConfigUpdateOne) ClearGitTag() *ServiceConfigUpdateOne {
	_u.mutation.ClearGitTag()
	return _u
}

// SetHosts sets the "hosts" field.
func (_u *ServiceConfigUpdateOne) SetHosts(v []schema.HostSpec) *ServiceConfigUpdateOne {
	_u.mutation.SetHosts(v)
	return _u
}

// AppendHosts appends value to the "hosts" field.
func (_u *ServiceConfigUpdateOne) AppendHosts(v []schema.HostSpec) *ServiceConfigUpdateOne {
	_u.mutation.AppendHosts(v)
	return _u
}

// ClearHosts clears the value of the "hosts" field.
func (_u *ServiceConfigUpdateOne) ClearHosts() *ServiceConfigUpdateOne {
	_u.mutation.ClearHosts()
	return _u
}

// SetPorts sets the "ports" field.
func (_u *ServiceConfigUpdateOne) SetPorts(v []schema.PortSpec) *ServiceConfigUpdateOne {
	_u.mutation.SetPorts(v)
	return _u
}

// AppendPorts appends value to the "ports" field.
func (_u *ServiceConfigUpdateOne) AppendPorts(v []schema.PortSpec) *ServiceConfigUpdateOne {
	_u.mutation.AppendPorts(v)
	return _u
}

// ClearPorts clears the value of the "ports" field.
func (_u *ServiceConfigUpdateOne) ClearPorts() *ServiceConfigUpdateOne {
	_u.mutation.ClearPorts()
	return _u
}

// SetReplicas sets the "replicas" field.
func (_u *ServiceConfigUpdateOne) SetReplicas(v int32) *ServiceConfigUpdateOne {
	_u.mutation.ResetReplicas()
	_u.mutation.SetReplicas(v)
	return _u
}

// SetNillableReplicas sets the "replicas" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableReplicas(v *int32) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetReplicas(*v)
	}
	return _u
}

// AddReplicas adds value to the "replicas" field.
func (_u *ServiceConfigUpdateOne) AddReplicas(v int32) *ServiceConfigUpdateOne {
	_u.mutation.AddReplicas(v)
	return _u
}

// SetAutoDeploy sets the "auto_deploy" field.
func (_u *ServiceConfigUpdateOne) SetAutoDeploy(v bool) *ServiceConfigUpdateOne {
	_u.mutation.SetAutoDeploy(v)
	return _u
}

// SetNillableAutoDeploy sets the "auto_deploy" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableAutoDeploy(v *bool) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetAutoDeploy(*v)
	}
	return _u
}

// SetRailpackBuilderInstallCommand sets the "railpack_builder_install_command" field.
func (_u *ServiceConfigUpdateOne) SetRailpackBuilderInstallCommand(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetRailpackBuilderInstallCommand(v)
	return _u
}

// SetNillableRailpackBuilderInstallCommand sets the "railpack_builder_install_command" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableRailpackBuilderInstallCommand(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetRailpackBuilderInstallCommand(*v)
	}
	return _u
}

// ClearRailpackBuilderInstallCommand clears the value of the "railpack_builder_install_command" field.
func (_u *ServiceConfigUpdateOne) ClearRailpackBuilderInstallCommand() *ServiceConfigUpdateOne {
	_u.mutation.ClearRailpackBuilderInstallCommand()
	return _u
}

// SetRailpackBuilderBuildCommand sets the "railpack_builder_build_command" field.
func (_u *ServiceConfigUpdateOne) SetRailpackBuilderBuildCommand(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetRailpackBuilderBuildCommand(v)
	return _u
}

// SetNillableRailpackBuilderBuildCommand sets the "railpack_builder_build_command" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableRailpackBuilderBuildCommand(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetRailpackBuilderBuildCommand(*v)
	}
	return _u
}

// ClearRailpackBuilderBuildCommand clears the value of the "railpack_builder_build_command" field.
func (_u *ServiceConfigUpdateOne) ClearRailpackBuilderBuildCommand() *ServiceConfigUpdateOne {
	_u.mutation.ClearRailpackBuilderBuildCommand()
	return _u
}

// SetRunCommand sets the "run_command" field.
func (_u *ServiceConfigUpdateOne) SetRunCommand(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetRunCommand(v)
	return _u
}

// SetNillableRunCommand sets the "run_command" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableRunCommand(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetRunCommand(*v)
	}
	return _u
}

// ClearRunCommand clears the value of the "run_command" field.
func (_u *ServiceConfigUpdateOne) ClearRunCommand() *ServiceConfigUpdateOne {
	_u.mutation.ClearRunCommand()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ServiceConfigUpdateOne) SetIsPublic(v bool) *ServiceConfigUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableIsPublic(v *bool) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ServiceConfigUpdateOne) SetImage(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableImage(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *ServiceConfigUpdateOne) ClearImage() *ServiceConfigUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetDefinitionVersion sets the "definition_version" field.
func (_u *ServiceConfigUpdateOne) SetDefinitionVersion(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetDefinitionVersion(v)
	return _u
}

// SetNillableDefinitionVersion sets the "definition_version" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableDefinitionVersion(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetDefinitionVersion(*v)
	}
	return _u
}

// ClearDefinitionVersion clears the value of the "definition_version" field.
func (_u *ServiceConfigUpdateOne) ClearDefinitionVersion() *ServiceConfigUpdateOne {
	_u.mutation.ClearDefinitionVersion()
	return _u
}

// SetDatabaseConfig sets the "database_config" field.
func (_u *ServiceConfigUpdateOne) SetDatabaseConfig(v *schema.DatabaseConfig) *ServiceConfigUpdateOne {
	_u.mutation.SetDatabaseConfig(v)
	return _u
}

// ClearDatabaseConfig clears the value of the "database_config" field.
func (_u *ServiceConfigUpdateOne) ClearDatabaseConfig() *ServiceConfigUpdateOne {
	_u.mutation.ClearDatabaseConfig()
	return _u
}

// SetS3BackupSourceID sets the "s3_backup_source_id" field.
func (_u *ServiceConfigUpdateOne) SetS3BackupSourceID(v uuid.UUID) *ServiceConfigUpdateOne {
	_u.mutation.SetS3BackupSourceID(v)
	return _u
}

// SetNillableS3BackupSourceID sets the "s3_backup_source_id" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableS3BackupSourceID(v *uuid.UUID) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetS3BackupSourceID(*v)
	}
	return _u
}

// ClearS3BackupSourceID clears the value of the "s3_backup_source_id" field.
func (_u *ServiceConfigUpdateOne) ClearS3BackupSourceID() *ServiceConfigUpdateOne {
	_u.mutation.ClearS3BackupSourceID()
	return _u
}

// SetS3BackupBucket sets the "s3_backup_bucket" field.
func (_u *ServiceConfigUpdateOne) SetS3BackupBucket(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetS3BackupBucket(v)
	return _u
}

// SetNillableS3BackupBucket sets the "s3_backup_bucket" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableS3BackupBucket(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetS3BackupBucket(*v)
	}
	return _u
}

// ClearS3BackupBucket clears the value of the "s3_backup_bucket" field.
func (_u *ServiceConfigUpdateOne) ClearS3BackupBucket() *ServiceConfigUpdateOne {
	_u.mutation.ClearS3BackupBucket()
	return _u
}

// SetBackupSchedule sets the "backup_schedule" field.
func (_u *ServiceConfigUpdateOne) SetBackupSchedule(v string) *ServiceConfigUpdateOne {
	_u.mutation.SetBackupSchedule(v)
	return _u
}

// SetNillableBackupSchedule sets the "backup_schedule" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableBackupSchedule(v *string) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetBackupSchedule(*v)
	}
	return _u
}

// SetBackupRetentionCount sets the "backup_retention_count" field.
func (_u *ServiceConfigUpdateOne) SetBackupRetentionCount(v int) *ServiceConfigUpdateOne {
	_u.mutation.ResetBackupRetentionCount()
	_u.mutation.SetBackupRetentionCount(v)
	return _u
}

// SetNillableBackupRetentionCount sets the "backup_retention_count" field if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableBackupRetentionCount(v *int) *ServiceConfigUpdateOne {
	if v != nil {
		_u.SetBackupRetentionCount(*v)
	}
	return _u
}

// AddBackupRetentionCount adds value to the "backup_retention_count" field.
func (_u *ServiceConfigUpdateOne) AddBackupRetentionCount(v int) *ServiceConfigUpdateOne {
	_u.mutation.AddBackupRetentionCount(v)
	return _u
}

// SetVolumes sets the "volumes" field.
func (_u *ServiceConfigUpdateOne) SetVolumes(v []schema.ServiceVolume) *ServiceConfigUpdateOne {
	_u.mutation.SetVolumes(v)
	return _u
}

// AppendVolumes appends value to the "volumes" field.
func (_u *ServiceConfigUpdateOne) AppendVolumes(v []schema.ServiceVolume) *ServiceConfigUpdateOne {
	_u.mutation.AppendVolumes(v)
	return _u
}

// ClearVolumes clears the value of the "volumes" field.
func (_u *ServiceConfigUpdateOne) ClearVolumes() *ServiceConfigUpdateOne {
	_u.mutation.ClearVolumes()
	return _u
}

// SetSecurityContext sets the "security_context" field.
func (_u *ServiceConfigUpdateOne) SetSecurityContext(v *schema.SecurityContext) *ServiceConfigUpdateOne {
	_u.mutation.SetSecurityContext(v)
	return _u
}

// ClearSecurityContext clears the value of the "security_context" field.
func (_u *ServiceConfigUpdateOne) ClearSecurityContext() *ServiceConfigUpdateOne {
	_u.mutation.ClearSecurityContext()
	return _u
}

// SetHealthCheck sets the "health_check" field.
func (_u *ServiceConfigUpdateOne) SetHealthCheck(v *schema.HealthCheck) *ServiceConfigUpdateOne {
	_u.mutation.SetHealthCheck(v)
	return _u
}

// ClearHealthCheck clears the value of the "health_check" field.
func (_u *ServiceConfigUpdateOne) ClearHealthCheck() *ServiceConfigUpdateOne {
	_u.mutation.ClearHealthCheck()
	return _u
}

// SetVariableMounts sets the "variable_mounts" field.
func (_u *ServiceConfigUpdateOne) SetVariableMounts(v []*schema.VariableMount) *ServiceConfigUpdateOne {
	_u.mutation.SetVariableMounts(v)
	return _u
}

// AppendVariableMounts appends value to the "variable_mounts" field.
func (_u *ServiceConfigUpdateOne) AppendVariableMounts(v []*schema.VariableMount) *ServiceConfigUpdateOne {
	_u.mutation.AppendVariableMounts(v)
	return _u
}

// ClearVariableMounts clears the value of the "variable_mounts" field.
func (_u *ServiceConfigUpdateOne) ClearVariableMounts() *ServiceConfigUpdateOne {
	_u.mutation.ClearVariableMounts()
	return _u
}

// SetProtectedVariables sets the "protected_variables" field.
func (_u *ServiceConfigUpdateOne) SetProtectedVariables(v []string) *ServiceConfigUpdateOne {
	_u.mutation.SetProtectedVariables(v)
	return _u
}

// AppendProtectedVariables appends value to the "protected_variables" field.
func (_u *ServiceConfigUpdateOne) AppendProtectedVariables(v []string) *ServiceConfigUpdateOne {
	_u.mutation.AppendProtectedVariables(v)
	return _u
}

// ClearProtectedVariables clears the value of the "protected_variables" field.
func (_u *ServiceConfigUpdateOne) ClearProtectedVariables() *ServiceConfigUpdateOne {
	_u.mutation.ClearProtectedVariables()
	return _u
}

// SetInitContainers sets the "init_containers" field.
func (_u *ServiceConfigUpdateOne) SetInitContainers(v []*schema.InitContainer) *ServiceConfigUpdateOne {
	_u.mutation.SetInitContainers(v)
	return _u
}

// AppendInitContainers appends value to the "init_containers" field.
func (_u *ServiceConfigUpdateOne) AppendInitContainers(v []*schema.InitContainer) *ServiceConfigUpdateOne {
	_u.mutation.AppendInitContainers(v)
	return _u
}

// ClearInitContainers clears the value of the "init_containers" field.
func (_u *ServiceConfigUpdateOne) ClearInitContainers() *ServiceConfigUpdateOne {
	_u.mutation.ClearInitContainers()
	return _u
}

// SetResources sets the "resources" field.
func (_u *ServiceConfigUpdateOne) SetResources(v *schema.Resources) *ServiceConfigUpdateOne {
	_u.mutation.SetResources(v)
	return _u
}

// ClearResources clears the value of the "resources" field.
func (_u *ServiceConfigUpdateOne) ClearResources() *ServiceConfigUpdateOne {
	_u.mutation.ClearResources()
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *ServiceConfigUpdateOne) SetService(v *Service) *ServiceConfigUpdateOne {
	return _u.SetServiceID(v.ID)
}

// SetS3BackupSourcesID sets the "s3_backup_sources" edge to the S3 entity by ID.
func (_u *ServiceConfigUpdateOne) SetS3BackupSourcesID(id uuid.UUID) *ServiceConfigUpdateOne {
	_u.mutation.SetS3BackupSourcesID(id)
	return _u
}

// SetNillableS3BackupSourcesID sets the "s3_backup_sources" edge to the S3 entity by ID if the given value is not nil.
func (_u *ServiceConfigUpdateOne) SetNillableS3BackupSourcesID(id *uuid.UUID) *ServiceConfigUpdateOne {
	if id != nil {
		_u = _u.SetS3BackupSourcesID(*id)
	}
	return _u
}

// SetS3BackupSources sets the "s3_backup_sources" edge to the S3 entity.
func (_u *ServiceConfigUpdateOne) SetS3BackupSources(v *S3) *ServiceConfigUpdateOne {
	return _u.SetS3BackupSourcesID(v.ID)
}

// Mutation returns the ServiceConfigMutation object of the builder.
func (_u *ServiceConfigUpdateOne) Mutation() *ServiceConfigMutation {
	return _u.mutation
}

// ClearService clears the "service" edge to the Service entity.
func (_u *ServiceConfigUpdateOne) ClearService() *ServiceConfigUpdateOne {
	_u.mutation.ClearService()
	return _u
}

// ClearS3BackupSources clears the "s3_backup_sources" edge to the S3 entity.
func (_u *ServiceConfigUpdateOne) ClearS3BackupSources() *ServiceConfigUpdateOne {
	_u.mutation.ClearS3BackupSources()
	return _u
}

// Where appends a list predicates to the ServiceConfigUpdate builder.
func (_u *ServiceConfigUpdateOne) Where(ps ...predicate.ServiceConfig) *ServiceConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceConfigUpdateOne) Select(field string, fields ...string) *ServiceConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceConfig entity.
func (_u *ServiceConfigUpdateOne) Save(ctx context.Context) (*ServiceConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceConfigUpdateOne) SaveX(ctx context.Context) *ServiceConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := serviceconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Builder(); ok {
		if err := serviceconfig.BuilderValidator(v); err != nil {
			return &ValidationError{Name: "builder", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.builder": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RailpackProvider(); ok {
		if err := serviceconfig.RailpackProviderValidator(v); err != nil {
			return &ValidationError{Name: "railpack_provider", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.railpack_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RailpackFramework(); ok {
		if err := serviceconfig.RailpackFrameworkValidator(v); err != nil {
			return &ValidationError{Name: "railpack_framework", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.railpack_framework": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthCheck(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "health_check", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.health_check": %w`, err)}
		}
	}
	if _u.mutation.ServiceCleared() && len(_u.mutation.ServiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ServiceConfig.service"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ServiceConfigUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ServiceConfigUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ServiceConfigUpdateOne) sqlSave(ctx context.Context) (_node *ServiceConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(serviceconfig.Table, serviceconfig.Columns, sqlgraph.NewFieldSpec(serviceconfig.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceconfig.FieldID)
		for _, f := range fields {
			if !serviceconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != serviceconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Builder(); ok {
		_spec.SetField(serviceconfig.FieldBuilder, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(serviceconfig.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.DockerBuilderDockerfilePath(); ok {
		_spec.SetField(serviceconfig.FieldDockerBuilderDockerfilePath, field.TypeString, value)
	}
	if _u.mutation.DockerBuilderDockerfilePathCleared() {
		_spec.ClearField(serviceconfig.FieldDockerBuilderDockerfilePath, field.TypeString)
	}
	if value, ok := _u.mutation.DockerBuilderBuildContext(); ok {
		_spec.SetField(serviceconfig.FieldDockerBuilderBuildContext, field.TypeString, value)
	}
	if _u.mutation.DockerBuilderBuildContextCleared() {
		_spec.ClearField(serviceconfig.FieldDockerBuilderBuildContext, field.TypeString)
	}
	if value, ok := _u.mutation.RailpackProvider(); ok {
		_spec.SetField(serviceconfig.FieldRailpackProvider, field.TypeEnum, value)
	}
	if _u.mutation.RailpackProviderCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackProvider, field.TypeEnum)
	}
	if value, ok := _u.mutation.RailpackFramework(); ok {
		_spec.SetField(serviceconfig.FieldRailpackFramework, field.TypeEnum, value)
	}
	if _u.mutation.RailpackFrameworkCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackFramework, field.TypeEnum)
	}
	if value, ok := _u.mutation.GitBranch(); ok {
		_spec.SetField(serviceconfig.FieldGitBranch, field.TypeString, value)
	}
	if _u.mutation.GitBranchCleared() {
		_spec.ClearField(serviceconfig.FieldGitBranch, field.TypeString)
	}
	if value, ok := _u.mutation.GitTag(); ok {
		_spec.SetField(serviceconfig.FieldGitTag, field.TypeString, value)
	}
	if _u.mutation.GitTagCleared() {
		_spec.ClearField(serviceconfig.FieldGitTag, field.TypeString)
	}
	if value, ok := _u.mutation.Hosts(); ok {
		_spec.SetField(serviceconfig.FieldHosts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHosts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldHosts, value)
		})
	}
	if _u.mutation.HostsCleared() {
		_spec.ClearField(serviceconfig.FieldHosts, field.TypeJSON)
	}
	if value, ok := _u.mutation.Ports(); ok {
		_spec.SetField(serviceconfig.FieldPorts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPorts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldPorts, value)
		})
	}
	if _u.mutation.PortsCleared() {
		_spec.ClearField(serviceconfig.FieldPorts, field.TypeJSON)
	}
	if value, ok := _u.mutation.Replicas(); ok {
		_spec.SetField(serviceconfig.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedReplicas(); ok {
		_spec.AddField(serviceconfig.FieldReplicas, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AutoDeploy(); ok {
		_spec.SetField(serviceconfig.FieldAutoDeploy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RailpackBuilderInstallCommand(); ok {
		_spec.SetField(serviceconfig.FieldRailpackBuilderInstallCommand, field.TypeString, value)
	}
	if _u.mutation.RailpackBuilderInstallCommandCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackBuilderInstallCommand, field.TypeString)
	}
	if value, ok := _u.mutation.RailpackBuilderBuildCommand(); ok {
		_spec.SetField(serviceconfig.FieldRailpackBuilderBuildCommand, field.TypeString, value)
	}
	if _u.mutation.RailpackBuilderBuildCommandCleared() {
		_spec.ClearField(serviceconfig.FieldRailpackBuilderBuildCommand, field.TypeString)
	}
	if value, ok := _u.mutation.RunCommand(); ok {
		_spec.SetField(serviceconfig.FieldRunCommand, field.TypeString, value)
	}
	if _u.mutation.RunCommandCleared() {
		_spec.ClearField(serviceconfig.FieldRunCommand, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(serviceconfig.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(serviceconfig.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(serviceconfig.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.DefinitionVersion(); ok {
		_spec.SetField(serviceconfig.FieldDefinitionVersion, field.TypeString, value)
	}
	if _u.mutation.DefinitionVersionCleared() {
		_spec.ClearField(serviceconfig.FieldDefinitionVersion, field.TypeString)
	}
	if value, ok := _u.mutation.DatabaseConfig(); ok {
		_spec.SetField(serviceconfig.FieldDatabaseConfig, field.TypeJSON, value)
	}
	if _u.mutation.DatabaseConfigCleared() {
		_spec.ClearField(serviceconfig.FieldDatabaseConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.S3BackupBucket(); ok {
		_spec.SetField(serviceconfig.FieldS3BackupBucket, field.TypeString, value)
	}
	if _u.mutation.S3BackupBucketCleared() {
		_spec.ClearField(serviceconfig.FieldS3BackupBucket, field.TypeString)
	}
	if value, ok := _u.mutation.BackupSchedule(); ok {
		_spec.SetField(serviceconfig.FieldBackupSchedule, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupRetentionCount(); ok {
		_spec.SetField(serviceconfig.FieldBackupRetentionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBackupRetentionCount(); ok {
		_spec.AddField(serviceconfig.FieldBackupRetentionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Volumes(); ok {
		_spec.SetField(serviceconfig.FieldVolumes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVolumes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldVolumes, value)
		})
	}
	if _u.mutation.VolumesCleared() {
		_spec.ClearField(serviceconfig.FieldVolumes, field.TypeJSON)
	}
	if value, ok := _u.mutation.SecurityContext(); ok {
		_spec.SetField(serviceconfig.FieldSecurityContext, field.TypeJSON, value)
	}
	if _u.mutation.SecurityContextCleared() {
		_spec.ClearField(serviceconfig.FieldSecurityContext, field.TypeJSON)
	}
	if value, ok := _u.mutation.HealthCheck(); ok {
		_spec.SetField(serviceconfig.FieldHealthCheck, field.TypeJSON, value)
	}
	if _u.mutation.HealthCheckCleared() {
		_spec.ClearField(serviceconfig.FieldHealthCheck, field.TypeJSON)
	}
	if value, ok := _u.mutation.VariableMounts(); ok {
		_spec.SetField(serviceconfig.FieldVariableMounts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedVariableMounts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldVariableMounts, value)
		})
	}
	if _u.mutation.VariableMountsCleared() {
		_spec.ClearField(serviceconfig.FieldVariableMounts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProtectedVariables(); ok {
		_spec.SetField(serviceconfig.FieldProtectedVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProtectedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldProtectedVariables, value)
		})
	}
	if _u.mutation.ProtectedVariablesCleared() {
		_spec.ClearField(serviceconfig.FieldProtectedVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.InitContainers(); ok {
		_spec.SetField(serviceconfig.FieldInitContainers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedInitContainers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, serviceconfig.FieldInitContainers, value)
		})
	}
	if _u.mutation.InitContainersCleared() {
		_spec.ClearField(serviceconfig.FieldInitContainers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Resources(); ok {
		_spec.SetField(serviceconfig.FieldResources, field.TypeJSON, value)
	}
	if _u.mutation.ResourcesCleared() {
		_spec.ClearField(serviceconfig.FieldResources, field.TypeJSON)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   serviceconfig.ServiceTable,
			Columns: []string{serviceconfig.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   serviceconfig.ServiceTable,
			Columns: []string{serviceconfig.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.S3BackupSourcesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceconfig.S3BackupSourcesTable,
			Columns: []string{serviceconfig.S3BackupSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.S3BackupSourcesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceconfig.S3BackupSourcesTable,
			Columns: []string{serviceconfig.S3BackupSourcesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(s3.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ServiceConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{serviceconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
