// Code generated by ifacemaker; DO NOT EDIT.

package oauthserver_repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent"
)

// OAuthServerRepositoryInterface ...
type OAuthServerRepositoryInterface interface {
	CreateClient(ctx context.Context, input *CreateClientInput) (*ent.OAuthClient, error)
	GetClientByClientID(ctx context.Context, clientID string) (*ent.OAuthClient, error)
	TouchClientLastUsed(ctx context.Context, id uuid.UUID, now time.Time, minInterval time.Duration) error
	// DeleteOrphanClientsBefore removes registrations that never led to a grant.
	DeleteOrphanClientsBefore(ctx context.Context, before time.Time) (int, error)
	CreateCode(ctx context.Context, input *CreateCodeInput) (*ent.OAuthAuthorizationCode, error)
	GetCodeByHash(ctx context.Context, codeHash string) (*ent.OAuthAuthorizationCode, error)
	// MarkCodeUsed claims the code for one exchange. It reports false when another
	// exchange already claimed it, so a concurrent replay cannot win the race.
	MarkCodeUsed(ctx context.Context, id uuid.UUID, now time.Time, grantID uuid.UUID) (bool, error)
	DeleteCodesExpiredBefore(ctx context.Context, before time.Time) (int, error)
	CreateGrant(ctx context.Context, input *CreateGrantInput) (*ent.OAuthGrant, error)
	GetGrantByID(ctx context.Context, id uuid.UUID) (*ent.OAuthGrant, error)
	// ListGrantsByUser returns the user's active grants, newest first.
	ListGrantsByUser(ctx context.Context, userID uuid.UUID) ([]*ent.OAuthGrant, error)
	RevokeGrant(ctx context.Context, id uuid.UUID, now time.Time) error
	TouchGrantLastUsed(ctx context.Context, id uuid.UUID, now time.Time, minInterval time.Duration) error
	// CreateTokens writes an access and refresh pair atomically.
	CreateTokens(ctx context.Context, input *CreateTokensInput) error
	GetTokenByHash(ctx context.Context, tokenHash string) (*ent.OAuthGrantToken, error)
	// MarkTokenUsed retires a refresh token on rotation. It reports false when the
	// token was already retired, which is the reuse signal.
	MarkTokenUsed(ctx context.Context, id uuid.UUID, now time.Time) (bool, error)
	DeleteTokensExpiredOrUsedBefore(ctx context.Context, before time.Time) (int, error)
}
