// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_repository_github

import (
	"context"

	"github.com/google/go-github/v69/github"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/unbindapp/unbind-api/ent"
	"github.com/unbindapp/unbind-api/ent/githubinstallation"
	"github.com/unbindapp/unbind-api/ent/schema"
)

// NewGithubRepositoryMock creates a new instance of GithubRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGithubRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GithubRepositoryMock {
	mock := &GithubRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GithubRepositoryMock is an autogenerated mock type for the GithubRepositoryInterface type
type GithubRepositoryMock struct {
	mock.Mock
}

type GithubRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GithubRepositoryMock) EXPECT() *GithubRepositoryMock_Expecter {
	return &GithubRepositoryMock_Expecter{mock: &_m.Mock}
}

// CreateApp provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) CreateApp(ctx context.Context, uniqueUuid uuid.UUID, app *github.AppConfig, createdBy uuid.UUID) (*ent.GithubApp, error) {
	ret := _mock.Called(ctx, uniqueUuid, app, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateApp")
	}

	var r0 *ent.GithubApp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *github.AppConfig, uuid.UUID) (*ent.GithubApp, error)); ok {
		return returnFunc(ctx, uniqueUuid, app, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *github.AppConfig, uuid.UUID) *ent.GithubApp); ok {
		r0 = returnFunc(ctx, uniqueUuid, app, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubApp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *github.AppConfig, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uniqueUuid, app, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_CreateApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApp'
type GithubRepositoryMock_CreateApp_Call struct {
	*mock.Call
}

// CreateApp is a helper method to define mock.On call
//   - ctx context.Context
//   - uniqueUuid uuid.UUID
//   - app *github.AppConfig
//   - createdBy uuid.UUID
func (_e *GithubRepositoryMock_Expecter) CreateApp(ctx any, uniqueUuid any, app any, createdBy any) *GithubRepositoryMock_CreateApp_Call {
	return &GithubRepositoryMock_CreateApp_Call{Call: _e.mock.On("CreateApp", ctx, uniqueUuid, app, createdBy)}
}

func (_c *GithubRepositoryMock_CreateApp_Call) Run(run func(ctx context.Context, uniqueUuid uuid.UUID, app *github.AppConfig, createdBy uuid.UUID)) *GithubRepositoryMock_CreateApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *github.AppConfig
		if args[2] != nil {
			arg2 = args[2].(*github.AppConfig)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_CreateApp_Call) Return(githubApp *ent.GithubApp, err error) *GithubRepositoryMock_CreateApp_Call {
	_c.Call.Return(githubApp, err)
	return _c
}

func (_c *GithubRepositoryMock_CreateApp_Call) RunAndReturn(run func(ctx context.Context, uniqueUuid uuid.UUID, app *github.AppConfig, createdBy uuid.UUID) (*ent.GithubApp, error)) *GithubRepositoryMock_CreateApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetApp provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetApp(ctx context.Context) (*ent.GithubApp, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetApp")
	}

	var r0 *ent.GithubApp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ent.GithubApp, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ent.GithubApp); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubApp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApp'
type GithubRepositoryMock_GetApp_Call struct {
	*mock.Call
}

// GetApp is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GithubRepositoryMock_Expecter) GetApp(ctx any) *GithubRepositoryMock_GetApp_Call {
	return &GithubRepositoryMock_GetApp_Call{Call: _e.mock.On("GetApp", ctx)}
}

func (_c *GithubRepositoryMock_GetApp_Call) Run(run func(ctx context.Context)) *GithubRepositoryMock_GetApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetApp_Call) Return(githubApp *ent.GithubApp, err error) *GithubRepositoryMock_GetApp_Call {
	_c.Call.Return(githubApp, err)
	return _c
}

func (_c *GithubRepositoryMock_GetApp_Call) RunAndReturn(run func(ctx context.Context) (*ent.GithubApp, error)) *GithubRepositoryMock_GetApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetApps provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetApps(ctx context.Context, withInstallations bool) ([]*ent.GithubApp, error) {
	ret := _mock.Called(ctx, withInstallations)

	if len(ret) == 0 {
		panic("no return value specified for GetApps")
	}

	var r0 []*ent.GithubApp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]*ent.GithubApp, error)); ok {
		return returnFunc(ctx, withInstallations)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []*ent.GithubApp); ok {
		r0 = returnFunc(ctx, withInstallations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.GithubApp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, withInstallations)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetApps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApps'
type GithubRepositoryMock_GetApps_Call struct {
	*mock.Call
}

// GetApps is a helper method to define mock.On call
//   - ctx context.Context
//   - withInstallations bool
func (_e *GithubRepositoryMock_Expecter) GetApps(ctx any, withInstallations any) *GithubRepositoryMock_GetApps_Call {
	return &GithubRepositoryMock_GetApps_Call{Call: _e.mock.On("GetApps", ctx, withInstallations)}
}

func (_c *GithubRepositoryMock_GetApps_Call) Run(run func(ctx context.Context, withInstallations bool)) *GithubRepositoryMock_GetApps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetApps_Call) Return(githubApps []*ent.GithubApp, err error) *GithubRepositoryMock_GetApps_Call {
	_c.Call.Return(githubApps, err)
	return _c
}

func (_c *GithubRepositoryMock_GetApps_Call) RunAndReturn(run func(ctx context.Context, withInstallations bool) ([]*ent.GithubApp, error)) *GithubRepositoryMock_GetApps_Call {
	_c.Call.Return(run)
	return _c
}

// GetGithubAppByID provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetGithubAppByID(ctx context.Context, ID int64) (*ent.GithubApp, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetGithubAppByID")
	}

	var r0 *ent.GithubApp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*ent.GithubApp, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *ent.GithubApp); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubApp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetGithubAppByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGithubAppByID'
type GithubRepositoryMock_GetGithubAppByID_Call struct {
	*mock.Call
}

// GetGithubAppByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *GithubRepositoryMock_Expecter) GetGithubAppByID(ctx any, ID any) *GithubRepositoryMock_GetGithubAppByID_Call {
	return &GithubRepositoryMock_GetGithubAppByID_Call{Call: _e.mock.On("GetGithubAppByID", ctx, ID)}
}

func (_c *GithubRepositoryMock_GetGithubAppByID_Call) Run(run func(ctx context.Context, ID int64)) *GithubRepositoryMock_GetGithubAppByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetGithubAppByID_Call) Return(githubApp *ent.GithubApp, err error) *GithubRepositoryMock_GetGithubAppByID_Call {
	_c.Call.Return(githubApp, err)
	return _c
}

func (_c *GithubRepositoryMock_GetGithubAppByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (*ent.GithubApp, error)) *GithubRepositoryMock_GetGithubAppByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGithubAppByUUID provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetGithubAppByUUID(ctx context.Context, ID uuid.UUID) (*ent.GithubApp, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetGithubAppByUUID")
	}

	var r0 *ent.GithubApp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*ent.GithubApp, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *ent.GithubApp); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubApp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetGithubAppByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGithubAppByUUID'
type GithubRepositoryMock_GetGithubAppByUUID_Call struct {
	*mock.Call
}

// GetGithubAppByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *GithubRepositoryMock_Expecter) GetGithubAppByUUID(ctx any, ID any) *GithubRepositoryMock_GetGithubAppByUUID_Call {
	return &GithubRepositoryMock_GetGithubAppByUUID_Call{Call: _e.mock.On("GetGithubAppByUUID", ctx, ID)}
}

func (_c *GithubRepositoryMock_GetGithubAppByUUID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *GithubRepositoryMock_GetGithubAppByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetGithubAppByUUID_Call) Return(githubApp *ent.GithubApp, err error) *GithubRepositoryMock_GetGithubAppByUUID_Call {
	_c.Call.Return(githubApp, err)
	return _c
}

func (_c *GithubRepositoryMock_GetGithubAppByUUID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*ent.GithubApp, error)) *GithubRepositoryMock_GetGithubAppByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallationByID provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetInstallationByID(ctx context.Context, ID int64) (*ent.GithubInstallation, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallationByID")
	}

	var r0 *ent.GithubInstallation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*ent.GithubInstallation, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *ent.GithubInstallation); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubInstallation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetInstallationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallationByID'
type GithubRepositoryMock_GetInstallationByID_Call struct {
	*mock.Call
}

// GetInstallationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *GithubRepositoryMock_Expecter) GetInstallationByID(ctx any, ID any) *GithubRepositoryMock_GetInstallationByID_Call {
	return &GithubRepositoryMock_GetInstallationByID_Call{Call: _e.mock.On("GetInstallationByID", ctx, ID)}
}

func (_c *GithubRepositoryMock_GetInstallationByID_Call) Run(run func(ctx context.Context, ID int64)) *GithubRepositoryMock_GetInstallationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetInstallationByID_Call) Return(githubInstallation *ent.GithubInstallation, err error) *GithubRepositoryMock_GetInstallationByID_Call {
	_c.Call.Return(githubInstallation, err)
	return _c
}

func (_c *GithubRepositoryMock_GetInstallationByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (*ent.GithubInstallation, error)) *GithubRepositoryMock_GetInstallationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallationsByAppID provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetInstallationsByAppID(ctx context.Context, appID int64) ([]*ent.GithubInstallation, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallationsByAppID")
	}

	var r0 []*ent.GithubInstallation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*ent.GithubInstallation, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*ent.GithubInstallation); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.GithubInstallation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetInstallationsByAppID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallationsByAppID'
type GithubRepositoryMock_GetInstallationsByAppID_Call struct {
	*mock.Call
}

// GetInstallationsByAppID is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int64
func (_e *GithubRepositoryMock_Expecter) GetInstallationsByAppID(ctx any, appID any) *GithubRepositoryMock_GetInstallationsByAppID_Call {
	return &GithubRepositoryMock_GetInstallationsByAppID_Call{Call: _e.mock.On("GetInstallationsByAppID", ctx, appID)}
}

func (_c *GithubRepositoryMock_GetInstallationsByAppID_Call) Run(run func(ctx context.Context, appID int64)) *GithubRepositoryMock_GetInstallationsByAppID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetInstallationsByAppID_Call) Return(githubInstallations []*ent.GithubInstallation, err error) *GithubRepositoryMock_GetInstallationsByAppID_Call {
	_c.Call.Return(githubInstallations, err)
	return _c
}

func (_c *GithubRepositoryMock_GetInstallationsByAppID_Call) RunAndReturn(run func(ctx context.Context, appID int64) ([]*ent.GithubInstallation, error)) *GithubRepositoryMock_GetInstallationsByAppID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallationsByCreator provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) GetInstallationsByCreator(ctx context.Context, createdBy uuid.UUID) ([]*ent.GithubInstallation, error) {
	ret := _mock.Called(ctx, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallationsByCreator")
	}

	var r0 []*ent.GithubInstallation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*ent.GithubInstallation, error)); ok {
		return returnFunc(ctx, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*ent.GithubInstallation); ok {
		r0 = returnFunc(ctx, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.GithubInstallation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_GetInstallationsByCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallationsByCreator'
type GithubRepositoryMock_GetInstallationsByCreator_Call struct {
	*mock.Call
}

// GetInstallationsByCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - createdBy uuid.UUID
func (_e *GithubRepositoryMock_Expecter) GetInstallationsByCreator(ctx any, createdBy any) *GithubRepositoryMock_GetInstallationsByCreator_Call {
	return &GithubRepositoryMock_GetInstallationsByCreator_Call{Call: _e.mock.On("GetInstallationsByCreator", ctx, createdBy)}
}

func (_c *GithubRepositoryMock_GetInstallationsByCreator_Call) Run(run func(ctx context.Context, createdBy uuid.UUID)) *GithubRepositoryMock_GetInstallationsByCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_GetInstallationsByCreator_Call) Return(githubInstallations []*ent.GithubInstallation, err error) *GithubRepositoryMock_GetInstallationsByCreator_Call {
	_c.Call.Return(githubInstallations, err)
	return _c
}

func (_c *GithubRepositoryMock_GetInstallationsByCreator_Call) RunAndReturn(run func(ctx context.Context, createdBy uuid.UUID) ([]*ent.GithubInstallation, error)) *GithubRepositoryMock_GetInstallationsByCreator_Call {
	_c.Call.Return(run)
	return _c
}

// SetInstallationActive provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) SetInstallationActive(ctx context.Context, id int64, active bool) (*ent.GithubInstallation, error) {
	ret := _mock.Called(ctx, id, active)

	if len(ret) == 0 {
		panic("no return value specified for SetInstallationActive")
	}

	var r0 *ent.GithubInstallation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (*ent.GithubInstallation, error)); ok {
		return returnFunc(ctx, id, active)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) *ent.GithubInstallation); ok {
		r0 = returnFunc(ctx, id, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubInstallation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, id, active)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_SetInstallationActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInstallationActive'
type GithubRepositoryMock_SetInstallationActive_Call struct {
	*mock.Call
}

// SetInstallationActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - active bool
func (_e *GithubRepositoryMock_Expecter) SetInstallationActive(ctx any, id any, active any) *GithubRepositoryMock_SetInstallationActive_Call {
	return &GithubRepositoryMock_SetInstallationActive_Call{Call: _e.mock.On("SetInstallationActive", ctx, id, active)}
}

func (_c *GithubRepositoryMock_SetInstallationActive_Call) Run(run func(ctx context.Context, id int64, active bool)) *GithubRepositoryMock_SetInstallationActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_SetInstallationActive_Call) Return(githubInstallation *ent.GithubInstallation, err error) *GithubRepositoryMock_SetInstallationActive_Call {
	_c.Call.Return(githubInstallation, err)
	return _c
}

func (_c *GithubRepositoryMock_SetInstallationActive_Call) RunAndReturn(run func(ctx context.Context, id int64, active bool) (*ent.GithubInstallation, error)) *GithubRepositoryMock_SetInstallationActive_Call {
	_c.Call.Return(run)
	return _c
}

// SetInstallationSuspended provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) SetInstallationSuspended(ctx context.Context, id int64, suspended bool) (*ent.GithubInstallation, error) {
	ret := _mock.Called(ctx, id, suspended)

	if len(ret) == 0 {
		panic("no return value specified for SetInstallationSuspended")
	}

	var r0 *ent.GithubInstallation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (*ent.GithubInstallation, error)); ok {
		return returnFunc(ctx, id, suspended)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) *ent.GithubInstallation); ok {
		r0 = returnFunc(ctx, id, suspended)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubInstallation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, id, suspended)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_SetInstallationSuspended_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetInstallationSuspended'
type GithubRepositoryMock_SetInstallationSuspended_Call struct {
	*mock.Call
}

// SetInstallationSuspended is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - suspended bool
func (_e *GithubRepositoryMock_Expecter) SetInstallationSuspended(ctx any, id any, suspended any) *GithubRepositoryMock_SetInstallationSuspended_Call {
	return &GithubRepositoryMock_SetInstallationSuspended_Call{Call: _e.mock.On("SetInstallationSuspended", ctx, id, suspended)}
}

func (_c *GithubRepositoryMock_SetInstallationSuspended_Call) Run(run func(ctx context.Context, id int64, suspended bool)) *GithubRepositoryMock_SetInstallationSuspended_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_SetInstallationSuspended_Call) Return(githubInstallation *ent.GithubInstallation, err error) *GithubRepositoryMock_SetInstallationSuspended_Call {
	_c.Call.Return(githubInstallation, err)
	return _c
}

func (_c *GithubRepositoryMock_SetInstallationSuspended_Call) RunAndReturn(run func(ctx context.Context, id int64, suspended bool) (*ent.GithubInstallation, error)) *GithubRepositoryMock_SetInstallationSuspended_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertInstallation provides a mock function for the type GithubRepositoryMock
func (_mock *GithubRepositoryMock) UpsertInstallation(ctx context.Context, id int64, appID int64, accountID int64, accountLogin string, accountType githubinstallation.AccountType, accountURL string, repositorySelection githubinstallation.RepositorySelection, suspended bool, active bool, permissions schema.GithubInstallationPermissions, events []string) (*ent.GithubInstallation, error) {
	ret := _mock.Called(ctx, id, appID, accountID, accountLogin, accountType, accountURL, repositorySelection, suspended, active, permissions, events)

	if len(ret) == 0 {
		panic("no return value specified for UpsertInstallation")
	}

	var r0 *ent.GithubInstallation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int64, string, githubinstallation.AccountType, string, githubinstallation.RepositorySelection, bool, bool, schema.GithubInstallationPermissions, []string) (*ent.GithubInstallation, error)); ok {
		return returnFunc(ctx, id, appID, accountID, accountLogin, accountType, accountURL, repositorySelection, suspended, active, permissions, events)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int64, string, githubinstallation.AccountType, string, githubinstallation.RepositorySelection, bool, bool, schema.GithubInstallationPermissions, []string) *ent.GithubInstallation); ok {
		r0 = returnFunc(ctx, id, appID, accountID, accountLogin, accountType, accountURL, repositorySelection, suspended, active, permissions, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.GithubInstallation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, int64, string, githubinstallation.AccountType, string, githubinstallation.RepositorySelection, bool, bool, schema.GithubInstallationPermissions, []string) error); ok {
		r1 = returnFunc(ctx, id, appID, accountID, accountLogin, accountType, accountURL, repositorySelection, suspended, active, permissions, events)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GithubRepositoryMock_UpsertInstallation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertInstallation'
type GithubRepositoryMock_UpsertInstallation_Call struct {
	*mock.Call
}

// UpsertInstallation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - appID int64
//   - accountID int64
//   - accountLogin string
//   - accountType githubinstallation.AccountType
//   - accountURL string
//   - repositorySelection githubinstallation.RepositorySelection
//   - suspended bool
//   - active bool
//   - permissions schema.GithubInstallationPermissions
//   - events []string
func (_e *GithubRepositoryMock_Expecter) UpsertInstallation(ctx any, id any, appID any, accountID any, accountLogin any, accountType any, accountURL any, repositorySelection any, suspended any, active any, permissions any, events any) *GithubRepositoryMock_UpsertInstallation_Call {
	return &GithubRepositoryMock_UpsertInstallation_Call{Call: _e.mock.On("UpsertInstallation", ctx, id, appID, accountID, accountLogin, accountType, accountURL, repositorySelection, suspended, active, permissions, events)}
}

func (_c *GithubRepositoryMock_UpsertInstallation_Call) Run(run func(ctx context.Context, id int64, appID int64, accountID int64, accountLogin string, accountType githubinstallation.AccountType, accountURL string, repositorySelection githubinstallation.RepositorySelection, suspended bool, active bool, permissions schema.GithubInstallationPermissions, events []string)) *GithubRepositoryMock_UpsertInstallation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 githubinstallation.AccountType
		if args[5] != nil {
			arg5 = args[5].(githubinstallation.AccountType)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 githubinstallation.RepositorySelection
		if args[7] != nil {
			arg7 = args[7].(githubinstallation.RepositorySelection)
		}
		var arg8 bool
		if args[8] != nil {
			arg8 = args[8].(bool)
		}
		var arg9 bool
		if args[9] != nil {
			arg9 = args[9].(bool)
		}
		var arg10 schema.GithubInstallationPermissions
		if args[10] != nil {
			arg10 = args[10].(schema.GithubInstallationPermissions)
		}
		var arg11 []string
		if args[11] != nil {
			arg11 = args[11].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
			arg11,
		)
	})
	return _c
}

func (_c *GithubRepositoryMock_UpsertInstallation_Call) Return(githubInstallation *ent.GithubInstallation, err error) *GithubRepositoryMock_UpsertInstallation_Call {
	_c.Call.Return(githubInstallation, err)
	return _c
}

func (_c *GithubRepositoryMock_UpsertInstallation_Call) RunAndReturn(run func(ctx context.Context, id int64, appID int64, accountID int64, accountLogin string, accountType githubinstallation.AccountType, accountURL string, repositorySelection githubinstallation.RepositorySelection, suspended bool, active bool, permissions schema.GithubInstallationPermissions, events []string) (*ent.GithubInstallation, error)) *GithubRepositoryMock_UpsertInstallation_Call {
	_c.Call.Return(run)
	return _c
}
