apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkit-config
  namespace: {{ .Release.Namespace }}
data:
  buildkitd.toml: |
    [worker.oci]
    # Limit concurrency of build steps:
    max-parallelism = {{ .Values.maxParallelism }}
    gc = true
    reservedSpace = {{ .Values.gc.reservedSpace | quote }}
    maxUsedSpace = {{ .Values.gc.maxUsedSpace | quote }}
    minFreeSpace = {{ .Values.gc.minFreeSpace | quote }}

    {{- range .Values.registries }}
    [registry."{{ .url }}"]
    http = {{ if hasKey . "http" }}{{ .http }}{{ else }}true{{ end }}
    insecure = {{ if hasKey . "insecure" }}{{ .insecure }}{{ else }}true{{ end }}
    {{- if .ca }}
    ca = ["{{ .ca }}"]
    {{- end }}
    {{- end }}

    [frontend."dockerfile.v0"]
    enabled = true
